### ISSUE TITLE
Write data

### ISSUE THREAD

**Issue by jinesh08** [dalenguyen/firebase-wordpress-plugin#1]
How to write data to firebase database on click of a button

**Comment by dalenguyen** [comment]
Hi @jinesh08, can you be more specific? Like what kind of data, in which situation...?

**Comment by jinesh08** [comment]
I have 3 drop downs. And i want to send data to database on a button click in wordpress.

**Comment by dalenguyen** [comment]
Hi @jinesh08, that isn't enough information for me to figure it out. Please try to be as specific as possible. You can follow this guide as a start: https://stackoverflow.com/help/mcve
