### ISSUE TITLE
[Save on Firestore] changing the type of a information

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#100]
All the information that Contact form 7 sent to Firestore are comming like Type String...But i need to sent Bollean, Number, and other types...

This is my Contact form 7:

[hidden collectionName "Produtos"]
[hidden databaseType "firestore"]
[hidden criador class:getFirebaseUid "INVALID"]
[hidden dateType "data_nascimento"]
[hidden mapTypes "endereco"]
[hidden fileType "fotos"]

[file fotos__0 limit:1mb filetypes:gif|png|jpg|jpeg]

<p><label for="titulo">Nome do Serviço:</label>[text* titulo placeholder "Titulo do Serviço"]</p>
<p><label for="descricao">descricao:</label> [text* descricao placeholder "Diarista localizada..."]</p>
<p><label for="preco_original">Preço do Serviço:</label>[number preco_original id:preco_original min:1 max:10000000 placeholder "Preço"]</p>
<p><label for="preco">Preço:</label>[calculated preco id:preco "(preco_original*0,15)+preco_original"]

<p><label for="categoria">Categoria:</label> [radio categoria id:categoria default:1 "Aulas e Cursos" "Empreendedorismo" "Manutencao aparelhos" "Servicos Domesticos" "Construcao e Reformas" "Eventos e Festas" "Outro"]
<p><label for="categoria_id">Categoria_id:</label>[number categoria_id id:categoria_id min:1 max:10000000 placeholder "667"]</p>
<p><label for="sub_categoria">Sub Categoria:</label> [text* sub_categoria placeholder "Aulas de Matematica"]
<p><label for="subcategoria_id">subcategoria_id:</label>[number subcategoria_id id:subcategoria_id min:1 max:10000000 placeholder "669"]</p>

<p><label for="endereco">Endereço:</label>[text* endereco__endereco placeholder "Endereço (Rua, Avenida, Logradouro)"]
[text* endereco__bairro placeholder "Bairro"]
[text* endereco__cidade placeholder "Cidade"]
[text* endereco__estado placeholder "Estado"]
[number endereco__numero id:endereco__numero min:1 max:10000000 placeholder "Número"]
[text* endereco__complemento placeholder "Complemento"]
[number endereco__cep id:endereco__cep min:1 max:99999999 placeholder "CEP"]</p>

<p><label for="dias-disponiveis">Dias Disponiveis:</label>

<label for="segunda">Segunda-Feira:</label>[radio segunda id:segunda default:1 "True" "False"]
<label for="terca">Terça-Feira:</label>[radio terca id:terca default:1 "True" "False"]
<label for="quarta">Quarta-Feira:</label>[radio quarta id:quarta default:1 "True" "False"]
<label for="quinta">Quinta-Feira:</label>[radio quinta id:quinta default:1 "True" "False"]
<label for="sexta">Sexta-Feira:</label>[radio sexta id:sexta default:1 "True" "False"]
<label for="sabado">Sábado:</label>[radio sabado id:sabado default:1 "true" "false"]
<label for="domingo">Domingo:</label>[radio domingo id:domingo default:1 "True" "False"]

[submit id:if-data-submit "Cadastrar Serviço"]

------------------ This are Bollean Type ---------------
<p><label for="dias-disponiveis">Dias Disponiveis:</label>

<label for="segunda">Segunda-Feira:</label>[radio segunda id:segunda default:1 "True" "False"]
<label for="terca">Terça-Feira:</label>[radio terca id:terca default:1 "True" "False"]
<label for="quarta">Quarta-Feira:</label>[radio quarta id:quarta default:1 "True" "False"]
<label for="quinta">Quinta-Feira:</label>[radio quinta id:quinta default:1 "True" "False"]
<label for="sexta">Sexta-Feira:</label>[radio sexta id:sexta default:1 "True" "False"]
<label for="sabado">Sábado:</label>[radio sabado id:sabado default:1 "true" "false"]
<label for="domingo">Domingo:</label>[radio domingo id:domingo default:1 "True" "False"]
  

--------------------This are number type -----------------

<p><label for="preco_original">Preço do Serviço:</label>[number preco_original id:preco_original min:1 max:10000000 placeholder "Preço"]</p>
<p><label for="preco">Preço:</label>[calculated preco id:preco "(preco_original*0,15)+preco_original"]

<p><label for="categoria_id">Categoria_id:</label>[number categoria_id id:categoria_id min:1 max:10000000 placeholder "667"]</p>
<p><label for="subcategoria_id">subcategoria_id:</label>[number subcategoria_id id:subcategoria_id min:1 max:10000000 placeholder "669"]</p>

<p><label for="endereco">Endereço:</label>[text* endereco__endereco placeholder "Endereço (Rua, Avenida, Logradouro)"]
[number endereco__numero id:endereco__numero min:1 max:10000000 placeholder "Número"]
[number endereco__cep id:endereco__cep min:1 max:99999999 placeholder "CEP"]</p>

**Comment by dalenguyen** [comment]
Not sure if this one is still needed. Feel free to create another issue.
