### ISSUE TITLE
Need Documentation on Uploads to Firebase Storage and Registration via api

### ISSUE THREAD

**Issue by Bikerflyeradmin** [dalenguyen/firebase-wordpress-plugin#101]
I noticed in the new version there is support for uploading to firebase storage from WordPress, but I can't find anything about how to do this in the user guide.

Also, the user guide mentions the ability to register new users in WordPress when they sign up in firebase, but there is no documentation on the auth method and how the params need to be configured.

Can you please add some documentation on these features.

Thanks you.

**Comment by dalenguyen** [comment]
Hi @Bikerflyeradmin, you can utilize the search feature to search for the content that you want. 

![image](https://user-images.githubusercontent.com/14116156/89537073-cfeaf600-d7c6-11ea-893c-b984a085cc9c.png)

**Comment by Bikerflyeradmin** [comment]
I'm sorry, I actually found it just now!  Thank you!

**Comment by Bikerflyeradmin** [comment]
Dale, please tell me what type of authentication is needed to do this?

The Integrate Firebase PRO has its own Restful API endpoints that help to
create a new WordPress user.

In this scenario, when you have a mobile app, and you want to duplicate
user in WordPress, you can call the API to create a new User after user
register on your app.

Endpoint: POST https://example.com/firebase/v2/users/register
<https://your-website.com/firebase/v2/users/register>Example payload:
{
 username: 'dale',
 email: 'dale@dalenguyen.me',
 password: 'the-password'
}

**Comment by Bikerflyeradmin** [comment]
I see now you have the firebase user id sent as user_login.  Thank you.
