### ISSUE TITLE
SRC folder not found in the functions folder

### ISSUE THREAD

**Issue by nandofalcao** [dalenguyen/firebase-wordpress-plugin#102]
SRC folder not found in the functions folder from download file for the pro version

**Comment by dalenguyen** [comment]
Hi @nandofalcao , it doesn't have the src folder. The script is complied. You just need to follow the guide to deploy the functions.

**Comment by nandofalcao** [comment]
why is it compiled? 
I don't feel safe using something compiled. I need to know what is being done with my critical information. Right?

**Comment by dalenguyen** [comment]
I understand your point. It's a way protect the code and prevent people from tampering it. Actually most of products or scripts on the web are compiled and minified. It's a common practice.

You can have a test site to test the features. The functions are only for WP Dashboard management, you can use it on the frontend without installing the functions. 

And you can always write your own functions, if you want to have a totally control over it.
