### ISSUE TITLE
Registration form returns userId required but secretly registers the user anyway

### ISSUE THREAD

**Issue by Bikerflyeradmin** [dalenguyen/firebase-wordpress-plugin#104]
When I use the shortcode in your user guide to create a registration form, no matter what it always returns the error "userId required"

But when I check in the dashboard it registered the user.  

So users will not know they are registered because they get the error.  And if I take the error shortcode off, then the user will know nothing because the form does not redirect or do anything to let the user know it has been a success.

The registration form as it is is almost useless anyway, because it does not add the users to the user collection.  It just adds them to the authentication.

The form should add the users info to the user collection.

**Comment by dalenguyen** [comment]
Which version of the plugin are you using? If you are using an older version than v1.11.1, please update it.

**Comment by dalenguyen** [comment]
Should be fixed v1.12.0

**Comment by Bikerflyeradmin** [comment]
Thank you, Dale.  I really appreciate you.
