### ISSUE TITLE
I can`t download a update version of Firebase Pro

### ISSUE THREAD

**Issue by FernandoTangi** [dalenguyen/firebase-wordpress-plugin#106]
I made a purchase for Firebase + wordpress pro on April 13 2020.

However, when I went to download the upgrade (I logged in as fernandotangi@gmail.com) of the version and the page appears for me to buy the plugin again. Could you send me the pro version? or solve the problem on the page?

Best regards,

Fernando

**Comment by dalenguyen** [comment]
Hi @FernandoTangi, 

Your payment at that time was failed. It didn't go through the system.

**Comment by FernandoTangi** [comment]
Hi, Dale.


I understood what happened: I made a first payment with a credit card and it appeared that it was purchased. Then he started cashing in $ 5 all day 10.

I need you to cancel this payment number of card: (4004 8800 1113 ....), which appears to be automatic.

**Comment by FernandoTangi** [comment]
I had put another card... If you have a new problem, please contact me. 
I will send to your email, a print of the payments made on my credit card (every 10th).
