### ISSUE TITLE
Firebase Object

### ISSUE THREAD

**Issue by Rauljauregi** [dalenguyen/firebase-wordpress-plugin#107]
Hello to the whole community,

This is not really a problem, so if it is appropriate to move it to another location or delete it I will do so immediately.

Here's the thing. We are developing a web application that uses the Plugin to authenticate users. We don't use Firestore or Realtime data base. We want to extract the data from the user's session. To do this we try to access the Firebase Object using JavaScript and the instructions that Firebase provides.

We have created a shorcode that we add to the page where we want to retrieve the remaining data. But we are wondering what is the best way to do it and if we can share with the rest of the community this need, to solve it. Because there are some issues concerning JavaScript.

Thank you very much.

**Comment by dalenguyen** [comment]
Hi @Rauljauregi, I added a guide on how to add custom JavaScript on top of the plugin. You can give it try. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/add-custom-scripts.html

**Comment by Rauljauregi** [comment]
Thank you very much Dake,

This is s really awesome! I will share the result if our implementation

**Comment by Rauljauregi** [comment]
Hello, community,

It turns out that yesterday the wordpress 5.5. update was released, which involves different changes. Among them some related to JQuery. 

What is the right way to add a JQuery Script, and that is the best way according to the plugin and Wordpress 5.5 and later?

Thank you!

**Comment by TheWizardofWikacy** [comment]
I have been able to get the custom script to register using the code in the documentation of this plugin, but had to fix the relative file path for the script (that part is wrong in the code).
