### ISSUE TITLE
Do not update logged user

### ISSUE THREAD

**Issue by abreu1234** [dalenguyen/firebase-wordpress-plugin#108]
**Describe the bug**
I followed the tutorial on the demo site and created the contact form 7 form. It searches for the data of the user logged in as in the example, however when updating, it does not change in the firestore.
The same problem occurs on the demo page: https://wordpress.dalenguyen.me/firebase-account/

**Expected behavior**
Update the user document

**Screenshots**
The version of the plugin. PRO v1.11.1

**Comment by dalenguyen** [comment]
This is fixed in v1.12.0. I made an early release for you. Please go to https://firebase.dalenguyen.me and download it. 

Thanks for the bug reporting.
