### ISSUE TITLE
Word Press

### ISSUE THREAD

**Issue by jaott1** [dalenguyen/firebase-wordpress-plugin#11]
I have put in the short code and submit button but, I can not get it to link to the firebase site. Not sure what I'm doing wrong

**Comment by dalenguyen** [comment]
Hi @jaott1, can you take snapshots of your credentials page, login form, and any errors in the console if possible?. Thanks,

**Comment by jaott1** [comment]
Yes

**Comment by Bhargav0528** [comment]
![fblogin](https://user-images.githubusercontent.com/27493662/47961710-36f9da80-e036-11e8-8f44-86b2f5a29368.png)

Not able to Signup users , added the short code am I missing something?

**Comment by jaott1** [comment]
That us correctSent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Bhargav0528 <notifications@github.com> Date: 11/4/18  2:04 AM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Word Press (#11) 
Not able to Signup users , added the short code am I missing something?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dalenguyen/firebase-wordpress-plugin","title":"dalenguyen/firebase-wordpress-plugin","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dalenguyen/firebase-wordpress-plugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bhargav0528 in #11: ![fblogin](https://user-images.githubusercontent.com/27493662/47961710-36f9da80-e036-11e8-8f44-86b2f5a29368.png)\r\n\r\nNot able to Signup users , added the short code am I missing something?"}],"action":{"name":"View Issue","url":"https://github.com/dalenguyen/firebase-wordpress-plugin/issues/11#issuecomment-435650232"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/11#issuecomment-435650232",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/11#issuecomment-435650232",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [dalenguyen/firebase-wordpress-plugin] Word Press (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Bhargav0528**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Bhargav0528",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"dalenguyen/firebase-wordpress-plugin\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"dalenguyen/firebase-wordpress-plugin\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/11#issuecomment-435650232"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 403785400\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by dalenguyen** [comment]
> ![fblogin](https://user-images.githubusercontent.com/27493662/47961710-36f9da80-e036-11e8-8f44-86b2f5a29368.png)
> 
> Not able to Signup users , added the short code am I missing something?

It's a login shortcode. Are you able to log in? Please check the inspector if there is any error. Thanks,

**Comment by dalenguyen** [comment]
@jaott1 Can you clean the message? It's really hard for me to understand...

**Comment by dalenguyen** [comment]
Closed due to inactivity.
