### ISSUE TITLE
Can't connect and the webui not showing

### ISSUE THREAD

**Issue by Tsukasa88** [dalenguyen/firebase-wordpress-plugin#112]
Hi,
I'm using the last version but the error shows and older version also.
context :
I connect to wordpress as user with the Firebase.
After 10 or 15 days as firebase detects as i'm still connected but wordpress does not.
So when i want to reconnect the firebase webui login/signup is not showing.
![screeshot netalem login normal private](https://user-images.githubusercontent.com/36668874/91555090-a427df80-e930-11ea-8a1a-03e9379186b3.png)

**Comment by dalenguyen** [comment]
Hi @Tsukasa88, when user login, you can add sign out button, so they can logout. If you are currently logged in, the form won't show up. You can clear the cache of your page, then it will clear the login session.

**Comment by Tsukasa88** [comment]
Thank you adding logout works!
But clearing cache does not.

**Comment by dalenguyen** [comment]
Yah, I'm glad that it works :D
