### ISSUE TITLE
Display data from Firebase Realtime Database

### ISSUE THREAD

**Issue by satya-securemachines** [dalenguyen/firebase-wordpress-plugin#114]
Hi Dale, 

We have been trying to evaluating your plug-in for use in one of our pages. 

[realtime class=’your-class-name’ collection_name=’string’ document_name=’string’]

Since we are new to wordpress/firebase, request some info on "your-class-name" field in the shortcode you have mentioned to retrieve data from a realtime database in firestore?

Is this a local class in wordpress to style and format the data or is this a class name coming from firebase? Could you kindly share an example or info?

Note : We are able to use your plug-in to see data from the realtime database listed in the Setting>Firebase page of wordpress. It gets displayed. Also the login/logout shortcodes work in our test page. 

Thanks in advance, 

Best Regards,
Satya

**Comment by dalenguyen** [comment]
Hi @satya-securemachines, `your-class-name` is the CSS class for styling purposes in the frontend site. 

For more cases on showing realtime data on WordPress, you can take a look at the demo pages: 

https://wordpress.dalenguyen.me/ (Check the Realtime Database section)

Thanks,

**Comment by satya-securemachines** [comment]
Hi Dale,

Thanks for your response. Understood. i have created a css custom class using some examples. Am unable to display after this too. 

Could you kindly suggest what could be wrong?
(Thanks for the link, read the documentation, but could not figure out!)

I share below my screen shot from the setting page where data is retrieved

![image](https://user-images.githubusercontent.com/70796305/92308998-527df580-efbf-11ea-9c10-4d04535bf2ac.png)

My css-class is 

![image](https://user-images.githubusercontent.com/70796305/92308956-f7e49980-efbe-11ea-9a68-a8d19e99c31d.png)

And the short code(s) i tried in page is below

![image](https://user-images.githubusercontent.com/70796305/92309063-ce783d80-efbf-11ea-921b-c05d0274c6a3.png)

Thanks again,
Satya

**Comment by dalenguyen** [comment]
Hi Satya,

Which version of the plugin you are using?

Is there any log messages when you inspect the browser?

Do you have a test link that I can a look at?  

It could be because of the security rule for your database.

Note: class='p' will not apply to p tag. P is not a class name. 

Thanks,

**Comment by satya-securemachines** [comment]
Hi Dale, 

Thanks for your quick response. 

- Version : v0.7.0
- Error Code : None on page, even after adding [firebase_error class='your-class-name'][/firebase_error] 
- No security rule, read/write allowed

![image](https://user-images.githubusercontent.com/70796305/92310276-49deec80-efca-11ea-9c64-78bf04d4cfcc.png)

For "p" class, sorry i am not familiar with css/wordpress etc. Could you suggest what i need to use?

Thanks,
Satya

**Comment by dalenguyen** [comment]
Hi Satya,

You're using the Free version which doesn't have that feature. You can achieve it by adding custom JavaScript. 

If you are interested in the PRO version, you can get it at https://firebase.dalenguyen.me 

Thanks,

**Comment by satya-securemachines** [comment]
Hi Dale, 

Sure, we are considering buying the plug-in. However thought the read from realtime database was part of the evaluation version. 

Thanks,
Satya

**Comment by dalenguyen** [comment]
Yes, reading from realtime is a part of the free version. However, it's limited and the shortcode is different. 


https://wordpress.org/plugins/integrate-firebase/#%0Ahow%20can%20i%20show%20realtime%20database%20for%20a%20logged%20in%20user%3F%0A

**Comment by satya-securemachines** [comment]
Hi Dale, 

We have the pro version of your plug-in. 

How do we contact your for support?

Thanks,
Sayta

**Comment by dalenguyen** [comment]
Thank Satya for your support. For questions or issues, you can create a new ticket here for further support. Please provide details information for better assistance.
