### ISSUE TITLE
Firebase pluging breaks Nimble Page Builder plugin

### ISSUE THREAD

**Issue by SebastianKumor** [dalenguyen/firebase-wordpress-plugin#117]
**Describe the bug**
Integrate Firebase breaks my page builder witch makes it unusable and images wont load on the production site.

**To Reproduce**
1. get Nimble Page Builder plugin
2. build a simple page with title and image
3. activate Integrate Firebase and try go edit the page with nimble again

**Expected behavior**
I should be able to edit my page and the production page should be not broken

**Screenshots**
plugin version I used is 0.7.0

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**
 - OS: macOS catalinaa
 - Browser Firefox and safari
 - Version latest

**Additional context**

**Comment by dalenguyen** [comment]
Thank @SebastianKumor, I will take a look at this one.

**Comment by SebastianKumor** [comment]
@dalenguyen np, let me know if you need more data

**Comment by dalenguyen** [comment]
> @dalenguyen np, let me know if you need more data

Yes, if you have any snapshots on the error or console log error, it would be great.
