### ISSUE TITLE
Support for Firebase Auth

### ISSUE THREAD

**Issue by bobwol** [dalenguyen/firebase-wordpress-plugin#12]
Enhancement idea: provide support for Firebase Authentication feature out-of-the-box.

The use case is to use Firebase Authentication for mobile apps (this is ready) and for pwa apps (built using WordPress with this plugin and shortcodes).

**Comment by dalenguyen** [comment]
Hi @bobwol, could you please provide more detail on "provide support for Firebase Authentication feature out-of-the-box"? Thanks,

**Comment by bobwol** [comment]
Hi @dalenguyen 

Thanks for your follow up.
I installed the plugin and it works with Realtime and Firestore database (I can select in the dropdown option). But Firebase also have an Auth feature ready to use for authentication purposes.
This Auth feature works easily with mobile apps, but could work also with WordPress and PWA plugin.

See here: https://firebase.google.com/products/auth/

What do you think?

**Comment by dalenguyen** [comment]
This is now supported with PRO version at https://firebase.dalenguyen.me
