### ISSUE TITLE
Basic Authentication via API

### ISSUE THREAD

**Issue by TheWizardofWikacy** [dalenguyen/firebase-wordpress-plugin#122]
Are there new endpoints for basic authentication via the api, such as the endpoint for creating new user mentioned in your docs?  How could I allow my mobile app users to authenticate to wordpress in the app?

**Comment by dalenguyen** [comment]
There is none at the moment for basic authentication via API. What is your use case?

**Comment by TheWizardofWikacy** [comment]
I'm going to try to integrate the wordpress backend with my app as well,
login uses so they can add vendor products from the app, and was going to
log them in via the rest API but was wondering since the registration is
via a custom firebase endpoint perhaps the login is too.

**Comment by TheWizardofWikacy** [comment]
Also, when I use the shortcode to display realtime doc from query, it is
awesome because I can just have the doc I'd of post in app joined the the
site url to allow users to share links to their stories.  However, when
inside facebook webview the realtime doc does not load.  Would it help to
put the code in the header?

**Comment by dalenguyen** [comment]
It wouldn't help because the content wasn't there for preview. You can use an SEO plugin in order to generate a general preview for social media instead.

**Comment by TheWizardofWikacy** [comment]
Apart from preview, how could I get the firebase data to load on the page
of my website?  Facebook merely keeps a user in their webview she. They
click on the link.  But for some reason the firebase data does not load in
Facebook's webview (not talking about preview)

**Comment by dalenguyen** [comment]
The data is from firebase, it won't available at the time for preview on social media. The suitable solution is to use an SEO tool to create a general title, description, and feature image for the dynamic post.

**Comment by TheWizardofWikacy** [comment]
I believe I have found a way to do it.  Thank you.
