### ISSUE TITLE
v1.18 breaks Beaver Builder "Posts" module

### ISSUE THREAD

**Issue by bcole2433** [dalenguyen/firebase-wordpress-plugin#123]
**Describe the bug**
Using v1.16.0 works correctly. When updating to v1.18.0, the Beaver Builder "Posts" module does not display the posts. However, the posts are still clickable (see screenshot). Testing on a dev environment. The images in an Image Carousel are also not loading correctly. There are not other breaking changes other than these UI issues. When deactivating the plugin, the "Posts" module displays correctly as well as the Image Carousel.

UPDATE: Actually breaks the whole Beaver Builder drag and drop interface as well. Here is a link to Beaver Builder known incompatibilities - [Beaver Builder Link](https://docs.wpbeaverbuilder.com/beaver-builder/troubleshooting/debugging/known-beaver-builder-incompatibilities)

** Version**
The version of the plugin. E.g PRO v1.16.0

**Screenshots**
![Snip20201015_19](https://user-images.githubusercontent.com/19436925/96198813-b4107880-0f0a-11eb-9dc1-3deed8d3665f.png)
![Snip20201015_20](https://user-images.githubusercontent.com/19436925/96198851-c8ed0c00-0f0a-11eb-9327-434d0e21e818.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 10.15.7

Go to https://premierlacrosseleague.com to see v1.16.0 working correctly in production env.

**Comment by dalenguyen** [comment]
Thank @bcole2433, do you have a link for your dev environment? 

What configuration did you use for the Beaver Builder?

**Comment by dalenguyen** [comment]
@bcole2433 Just trying with the latest version of BB (v2.4.0.5). Everything seems working. It would be easier if you can send the plugin that you are using or provide access to the dev / test environment (dale@dalenguyen.me), so I can take a deeper look into the issue.

![image](https://user-images.githubusercontent.com/14116156/96201224-0b721100-0f2a-11eb-86fb-29bea5c60978.png)

**Comment by bcole2433** [comment]
Dev Site: http://plleague.staging.wpengine.com/

Using Beaver Builder Version 2.4.0.6 and also Beaver Themer Version 1.3.2.3

Screenshot of the error when opening up the builder:
[image: image.png]

Just Keep Livin',
Brenden Coleman
c: (267) 337-2260 I Blog <http://medium.com/@bcole2433/> | w: www.nativx.com

<http://www.instagram.com/brendencoleman33>
<http://www.linkedin.com/ln/brendencoleman>

**Comment by bcole2433** [comment]
Dev Site: http://plleague.staging.wpengine.com/

Using Beaver Builder Version 2.4.0.6 and also Beaver Themer Version 1.3.2.3

Screenshot of the error when opening up the builder:
![Snip20201015_22](https://user-images.githubusercontent.com/19436925/96204077-3eaba480-0f18-11eb-8e51-becea1241b17.png)

**Comment by dalenguyen** [comment]
Hi @bcole2433, if you send the credential for the test site to dale@dalenguyen.me, it would be great. 
![image](https://user-images.githubusercontent.com/14116156/96204273-e7b2c900-0f31-11eb-9db0-05c6990d784b.png)

**Comment by dalenguyen** [comment]
Or you can create another test site with only two plugins and check if it has the same error.

**Comment by dalenguyen** [comment]
Fixed in v1.19.0
