### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by Eccles82** [dalenguyen/firebase-wordpress-plugin#124]
Will there be a intergratin of Woocommerce on this plugin? If so, could you please tell a bit about what features that will be available?
I would very much like to have order data sendt from Wordpress Woocommerce to Firebase Realtime Database.

**Comment by dalenguyen** [comment]
Hi @Eccles82, there will be integration for Woocomerce. The features haven't been finalized yet. If you are interested in the Woocommerce extension. You can book a meeting in order to understand how you use the product. 

https://calendly.com/dalenguyen/60min

**Comment by dalenguyen** [comment]
The initial version of Woocommerce is released. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/extensions/woocommerce.html
