### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by chriswhystle** [dalenguyen/firebase-wordpress-plugin#125]
**Describe the bug**
Your sample documentation is very helpful thanks.  However, in your sample code one of the 'single quotes' ['] registers instead as an apostrophe, throwing an error.  It could be updated for clarity!

**To Reproduce**
1. Go to https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/retrieve-data.html
2. The code is in the sample code here:

`  // You can get the collectionName and documentName from the shortcode attribute
            const collectionName = 'users';
            const documentName = ‘document-1'`

It should be corrected to remove the apostrophe before document-1 and use single quote.

`  // You can get the collectionName and documentName from the shortcode attribute
            const collectionName = 'users';
            const documentName ='document-1'`

Thought this might help others using your docs! Thanks for the great plugin.

**Comment by dalenguyen** [comment]
Thank @chriswhystle, the typo is fixed.
