### ISSUE TITLE
Authenticating as Firebase user creates WP user but has no permissions on WP site

### ISSUE THREAD

**Issue by BetterAutomations** [dalenguyen/firebase-wordpress-plugin#126]
**Describe the bug**
I have the following settings in auth. When I login as a Google user, it creates the WP user but that user has no permissions to use the site. I have even changed that user to Administrator, tried two different browsers, removed/reinstalled the plugin, and cleared the cache and cookies. Please assist.

WP Firebase auth settings:
https://i.imgur.com/fMeIQ06.png

WP Firebase general settings:
https://i.imgur.com/cp0QFz8.png

Google Firebase settings:
https://i.imgur.com/K6P9MJE.png

User in WP:
https://i.imgur.com/VQeGLxC.png

User has no access to user content on WP. Cannot see links at top:
https://i.imgur.com/XlstiHv.png

Original WP-only admin can see links at top:
https://i.imgur.com/IToLmwU.png

**To Reproduce**
1. Add settings as above
2. Add a page to WordPress that only Administrators users may view
3. Login as new Google user
4. Assign Administrator to that user
5. Log out and back in again as the new user
6. Attempt to view the hidden page

**Expected behavior**
Firebase users should be treated the same as full WP users

**Screenshots**
The version of the plugin. PRO 1.19.0

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome and Microsoft Edge
 - Version
	Chrome 86.0.4240.111 (Official Build) (64-bit)
	Edge 86.0.622.51 (Official build) (64-bit)
	WordPress 5.5.3

**Additional context**

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, when a user logs in via Google, will they get the role as `Subscriber` or 'Customer'? Or do you have any other plugin that assigns different user roles?

If you have a test site, please send it to me via email, I can help to test it.

**Comment by BetterAutomations** [comment]
By default they get role of Customer. WooCommerce would assign Customer or if a subscription is purchased, would assign the role Subscriber. But that didn't even create any Firesbase username. Going through WCommerce only creates a WP username with Customer or Subscriber.

I will email the details.

**Comment by dalenguyen** [comment]
This is fixed in v1.20.0

**Comment by BetterAutomations** [comment]
Dale, I am seeing this again on versions 2.4.0 and 2.3.0. Please advise.
