### ISSUE TITLE
Load users in Dashboard is not working...

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#127]
**Describe the bug**
Im trying to export a csv of my users, but I`m getting "Could not load user data!"

How can I fix?

**Comment by dalenguyen** [comment]
Hi @mcollinar, is there any error in the console? And could you please provide a snapshot of the issue?

**Comment by mcollinar** [comment]
Hi man....This error...

Everything was working fine...
![Captura de Tela 2020-11-03 às 13 45 35](https://user-images.githubusercontent.com/35809337/98015318-6c7b5f00-1ddb-11eb-81a4-2fc8fdfcd9b8.png)
![Captura de Tela 2020-11-03 às 13 45 39](https://user-images.githubusercontent.com/35809337/98015346-70a77c80-1ddb-11eb-8a3b-bd735797bd4c.png)
![Captura de Tela 2020-11-03 às 13 46 52](https://user-images.githubusercontent.com/35809337/98015350-71401300-1ddb-11eb-9937-e4fc1e220585.png)
![Captura de Tela 2020-11-03 às 13 48 41](https://user-images.githubusercontent.com/35809337/98015354-72714000-1ddb-11eb-8584-528eae23c62a.png)

**Comment by dalenguyen** [comment]
Hi @mcollinar, looks like there's a misconfiguration in the Settings tab and cloud functions. Please check it again if cloud functions are in your Firebase project. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/intro/cloud-functions-deployment.html

**Comment by mcollinar** [comment]
Thank you!... I fixed the Key API...
