### ISSUE TITLE
The export users do not bring some informations

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#128]
Hi,

When I export the Users some information are missing in ".csv":

- Crested on
- Signed in

**Comment by dalenguyen** [comment]
Hi @mcollinar, I will check it. One thing to note is to sensor privacy information before posting images.

**Comment by mcollinar** [comment]
Ok....thanks to let me know...

**Comment by mcollinar** [comment]
Can you exclude the attachment, please?

**Comment by dalenguyen** [comment]
I can check it. It will be at the weekend though.

**Comment by mcollinar** [comment]
In fact I asked to delete what I posted ... I didn't realize I had customer information ...

What I need is to include the user information created and last time online

**Comment by dalenguyen** [comment]
@mcollinar this is fixed in v1.21.0
