### ISSUE TITLE
[firestore] shortcode not working

### ISSUE THREAD

**Issue by herohitler** [dalenguyen/firebase-wordpress-plugin#129]
**Describe the bug**
The shortcode [firestore] do not work, the database is connected successfully, I have checked throuhgh Settings>Firebase>Databases. But when accessing a document from shortcode, it doesn't work. [realtime] works fine

**Expected behavior**
firestore document should be displayed.

**Screenshots**
The version of the plugin. E.g 0.7.0 (Free Version)

**Additional context**
The shortcode for [realtime] works fine, but when using [firestore] it is an invalid shortcode!
Kindly resolve it as soon as possible!
Any help will be appreciated:)
Thanks in advance!

**Comment by dalenguyen** [comment]
Hi @herohitler, the firestore shortcode is not in the Free version. I will take a look at improving it later.
