### ISSUE TITLE
Syncing users overwritesall other child keys in database.

### ISSUE THREAD

**Issue by TheWizardofWikacy** [dalenguyen/firebase-wordpress-plugin#132]
I had to deactivate the user syncing feature, because everytime a user would login to the site, all the data they added in firebase would be over-witten with the data being synced from login.  Is there a way to just update the existing nodes?

For instance, a user sings up, and this is sent to firebse:

  wp-users:

        email
        displayName
        photoUrl
       etc...

If they then add more data in the app, such as background photo, about, etc.., when they login to the website again thru firebaseui_web,  all the new nodes created in firebase get deleted and set back to the original map.

Is there a way to prevent this?

**Comment by dalenguyen** [comment]
Hi @TheWizardofWikacy, please help provide the following information: 

- version of the plugin you are using
- type of database that you are using (realtime / firestore)
- snapshot of before and after the changes

**Comment by dalenguyen** [comment]
Should be fixed.

**Comment by TheWizardofWikacy** [comment]
Thank you.
