### ISSUE TITLE
Update the wordpress firebase functions with problems

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#136]
**Describe the bug**
Hi,

Im trying to update but i having this problem....
MacBook-Pro-de-Collina:functions mcollina$ firebase deploy --only functions --project novo-boca-a-boca

=== Deploying to 'novo-boca-a-boca'...

i  deploying functions
✔  functions: Finished running predeploy script.

Error: package.json in functions directory has an engines field which is unsupported. The only valid choices are: {"node": "8"} and {"node": "10"}.
MacBook-Pro-de-Collina:functions mcollina$ 

**To Reproduce**

**Expected behavior**

**Screenshots**
The version of the plugin. E.g PRO v0.5.5

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**

**Additional context**

**Comment by dalenguyen** [comment]
Hi @mcollinar, please make sure to update firebase-tools package to the latest version. 

You can try with

`npm i -g firebase-tools`

Then try it again. If it doesn't work, you can post the content of the file package.json here.

**Comment by dalenguyen** [comment]
Should be fixed now.
