### ISSUE TITLE
Save number to Firestore

### ISSUE THREAD

**Issue by hgalarreta** [dalenguyen/firebase-wordpress-plugin#138]
Hello, it would be great you can add the feature to upload a "Number" to firestore. Currently, everything is saved as string.

Thank you very much for your support.

**Comment by dalenguyen** [comment]
Hi @hgalarreta, it's updated. You can download v2.0.0 and give it a try. 

Guide: https://firebase-wordpress-docs.readthedocs.io/en/latest/database/save-data-realtime-firestore.html

```
[hidden integerTypes “age”]
```

https://firebase.dalenguyen.me

**Comment by hgalarreta** [comment]
Perfect. Thankssssss.
