### ISSUE TITLE
Error getting data from Firestore database using number data_fields in shortcode

### ISSUE THREAD

**Issue by rubenalonsoes** [dalenguyen/firebase-wordpress-plugin#139]
**Describe the bug**
Using for example this shortcode [firestore collection_name='ranking' document_name='from-queries' display_fields='user_real_name,ie_engagement'] when the display_fields are all strings is ok, but in this case that ie_engagement is a number the output is an error:
"e.includes is not a function"

**To Reproduce**
1. Use the shortcode [firestore collection_name='ranking' document_name='from-queries' display_fields='user_real_name,ie_engagement']
2. Use a Document with Number fields (or other that are not String)
3. Set the display_fields paraemters with that Not-String fields
4. See error: "e.includes is not a function"

**Expected behavior**
A output as a normal string/number (in decimal numbers it would be great to be able to define the number of decimals)

**Screenshots**
Sample: https://miposicionamientoweb.es/pruebas/?docId=rubenalonsoes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Plugin Version 2.0.0

**Additional context**
The database is about Instagram users, and the idea is get the data about the username indicated in the URL variable _docId_ (it would possible change the name of this variable for my own, for example "user"?)

Thanks!

**Comment by dalenguyen** [comment]
This is fixed in v2.1.0
https://wordpress.dalenguyen.me/dynamic-display-firestore-data-from-table/?docId=55fe5130-7a64-11ea-98e5-b9eb62c4e611
