### ISSUE TITLE
Extension/Support for Easy Digital Downloads (EDD) Platform

### ISSUE THREAD

**Issue by alexnasla** [dalenguyen/firebase-wordpress-plugin#149]
**Is your feature request related to a problem? Please describe.**
There is WooCommerce support but I'm using easy digital downloads and there seem to be some issues integrating that with Firebase. It would be amazing if there was support for it.

**Describe the solution you'd like**
An extension that directly supports using EDD with Firebase and my wordpress site.

**Describe alternatives you've considered**
I don't really have an alternative figured out, to be honest. 

**Which fields does it relate to?**
Firebase Auth, Realtime DB

**Comment by dalenguyen** [comment]
Hi @alexnasla, which issues are you having? 

And how should it work together?

**Comment by dalenguyen** [comment]
Closed due to inactivity.
