### ISSUE TITLE
How use shortcode to get Data

### ISSUE THREAD

**Issue by MizaelGalvez** [dalenguyen/firebase-wordpress-plugin#15]
hi Dale !!! 🥇 

![image](https://user-images.githubusercontent.com/3112701/51080491-e9cf6000-1699-11e9-99d5-c3c8699dc5a7.png)

how can i get the value of "Numero" whit a shortcode ?

give me a example please !!! :) 

Thaks !!! i dont understand the shortcode, im new in wordpress,  sorry !!!

i dont understand this ---> echo do_shortcode("[firebase_show_not_login class='your-class-name']YOUR HTML CODE[/firebase_show_not_login]");

**Comment by acelmec** [comment]
Dear, I am creating an Android APP through THUNKABLE using FrameWork with my WEB Page built in WORDPRESS. I needed to know if I can integrate the WORDPRESS user database in FIREBASE, so I could create a LOGIN in the Android APP. Thanks for your help!

**Comment by RichardValadares** [comment]
I have this same problem. Does anyone know how to help? I need a specific JSON field returned by shortcode.
How do I do that?

**Comment by dalenguyen** [comment]
It can be done through a custom shortcode. Read the user guide: https://firebase-wordpress-docs.readthedocs.io/en/latest/index.html
