### ISSUE TITLE
Display Video from url in firebase using display field option

### ISSUE THREAD

**Issue by TheWizardofWikacy** [dalenguyen/firebase-wordpress-plugin#150]
Hello,

Videos are becoming a major feature in our app, and often times a post in firebase has a gif or an mp4 video as the main image.  It would be nice to be able to display the video if the collection contains key mp4, or whatever the key is, else an image.  

I realize this may be a paid extension but it would be well worth it.

Thank you.

**Comment by dalenguyen** [comment]
Closed due to the customer resolving it.
