### ISSUE TITLE
failed to create function api-user

### ISSUE THREAD

**Issue by BetterAutomations** [dalenguyen/firebase-wordpress-plugin#151]
**Describe the bug**
Unable to deploy functions, I get the error below. I had noticed the wrong project ID in .firebaserc and package.json but updating that to match my own did not help. I also tried creating the api-user function first in the console, no good.

```
C:\GCP.fbase_wpress\functions>firebase deploy --only functions --project coop-dev

=== Deploying to 'coop-dev'...

i  deploying functions
+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (228.75 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: creating Node.js 12 function api-user(us-central)...
!  functions: failed to create function api-user
HTTP Error: 403, Permission denied on 'locations/us-central' (or it may not exist)

Functions deploy had errors with the following functions:
        api-user(us-central)

To try redeploying those functions, run:
    firebase deploy --only "functions:api.user"

To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```

**To Reproduce**
1. Follow these directions:
https://firebase-wordpress-docs.readthedocs.io/en/latest/intro/cloud-functions-deployment.html

**Expected behavior**
Should upload the functions to GCP

**Screenshots**
Version 2.4.0

**Screenshots**
No screenshot

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19042.804

**Additional context**

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, can you take a snapshot of your firebase functions tab? 

![image](https://user-images.githubusercontent.com/14116156/109585565-bd713a80-7ad1-11eb-89f7-793eb5291387.png)

**Comment by BetterAutomations** [comment]
![image](https://user-images.githubusercontent.com/67400711/109634596-6db56200-7b17-11eb-8629-6aefa4f7e8e7.png)

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, that's the google cloud functions. Firebase cloud functions is little bit different. Can you check it in https://console.firebase.google.com/?

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, I saw that you have `api-user` in it. Is it the old one? Can you add dungnq@itbox4vn.com to your firebase dev environment, I can help to debug it.

**Comment by BetterAutomations** [comment]
Yes as mentioned above, I created tried creating the api-user function first in the console. I have added your email. Kindly note any changes so that I can make the same changes in Prod.

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, can you go to https://console.firebase.google.com and add my email there. I can see your google cloud, but not in firebase. 

![image](https://user-images.githubusercontent.com/14116156/109979192-9f235e80-7ccc-11eb-8595-bc770ad46854.png)

**Comment by BetterAutomations** [comment]
Added
![image](https://user-images.githubusercontent.com/67400711/110038402-b59dda00-7d0d-11eb-84ba-2d89c7c83ddb.png)

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, I saw that you have regions in your config. There is a typo. I should be `us-central1` not `us-central`. And for one region, you don't need to set it at all. You can unset it. 

```
firebase functions:config:unset regions --project coop-dev-805ec
```

![image](https://user-images.githubusercontent.com/14116156/110044153-a8d1b400-7d16-11eb-8f28-756d99d2ff73.png)

I edited the regions & redeploy them. It works. 

![image](https://user-images.githubusercontent.com/14116156/110044487-36ad9f00-7d17-11eb-8b09-d1d41ca3eafe.png)

**Comment by BetterAutomations** [comment]
Oh thank you. Where was this typo introduced? I don't recall typing that.

**Comment by BetterAutomations** [comment]
I'm unable to repeat your success. Please advise.

```
C:\GCP.fbase_wpress\functions>firebase deploy --only functions --project coop-dev-805ec

=== Deploying to 'coop-dev-805ec'...

i  deploying functions
+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (228.73 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: updating Node.js 12 function api-user(us-central1)...
i  functions: updating Node.js 12 function api-database(us-central1)...
i  functions: updating Node.js 12 function api-message(us-central1)...
+  functions[api-message(us-central1)]: Successful update operation.
+  functions[api-database(us-central1)]: Successful update operation.

Functions deploy had errors with the following functions:
        api-user(us-central1)

To try redeploying those functions, run:
    firebase deploy --only "functions:api.user"

To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.

C:\GCP.fbase_wpress\functions>firebase functions:config:unset regions --project coop-dev-805ec
+  Environment updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions


C:\GCP.fbase_wpress\functions>firebase deploy --only "functions:api.user"

=== Deploying to 'coop-dev-805ec'...

i  deploying functions
+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (228.73 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: updating Node.js 12 function api-user(us-central1)...

Functions deploy had errors with the following functions:
        api-user(us-central1)

To try redeploying those functions, run:
    firebase deploy --only "functions:api.user"

To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.

C:\GCP.fbase_wpress\functions>
```

**Comment by dalenguyen** [comment]
Hi @BetterAutomations, please delete your existing function in Firebase and try to deploy it again.

**Comment by BetterAutomations** [comment]
Thank you, that seemed to work.
