### ISSUE TITLE
Incomplete Plugin

### ISSUE THREAD

**Issue by 8HPhil** [dalenguyen/firebase-wordpress-plugin#154]
**Is your feature request related to a problem? Please describe.**
I can not check in my app which membership users have access to. Therefore, i can not create proper content brackets in my app.

**Describe the solution you'd like**
under the users, show which active memberships they have or under memberships, show the currently active users

**Comment by dalenguyen** [comment]
Hi @8HPhil, which version of the plugin are you using? 

Can you explain more on this one? `I can not check in my app which membership users have access to`? 

If you have snapshot of how active membership show under users, it would be great.

**Comment by 8HPhil** [comment]
Hi Dale,

I’d love to. I can even send you the plugins to help you do it.

Woocommerce has two extension… Memberships and Subscriptions…

WooCommerce allows you to hide data behind Memberships… When a user starts(purchases) a subscription, it comes with a membership.. The membership is what gives people access to more content..

Subscription is the paying process — Membership is what you pay for.  In my case, we have multiple apps. You can start a subscription to activate a membership to the app. I need to be able to tell which memberships people have active. Since a membership has its own tab, you can see which are active that way?

Since membership timelines are determined by the length of the subscription, you need both.. 

Example: a 1 month subscription will give me access to a membership for 1 month as long as I keep paying the reoccurring subscription.

I’ve bcc’ed your email so you can reply directly...

I’ll send screenshots to your email.

**Comment by dalenguyen** [comment]
This is deployed.
