### ISSUE TITLE
Installation of Plugin

### ISSUE THREAD

**Issue by orbify** [dalenguyen/firebase-wordpress-plugin#16]
I am having a few issues - I was wondering if someone could kindly help me.  

1.  I logged into my Wordpress website, searched for "Integrate Firebase". 
2.  Clicked on "Install" for "Integrate Firebase".
3.  Went into Plugins and clicked "Activate" for "Integrate Firebase" plugin.   
4.  Went to Settings > Firebase and added all my Firebase credentials.  
5.  Added short code into a page:

[firebase_login][/firebase_login]

6.  A place for typing in "Email" & "Password" shows up. 
7.  I enter in my "Email" & "Password". 
8.  Nothing happens... 

I guess what I wanted to know is - have I done everything correctly?

Is there a step I have missed?

Thank you!

![image](https://user-images.githubusercontent.com/48887917/54882572-c4956580-4e31-11e9-9df2-eb6aa16bf959.png)

![image](https://user-images.githubusercontent.com/48887917/54882585-de36ad00-4e31-11e9-93a8-1f0053a6d9ff.png)

Update #1 >>>>>

When I click on "Database" in "Firebase" under "Settings" - I successfully get this:

![image](https://user-images.githubusercontent.com/48887917/54883246-38d40700-4e3a-11e9-8a0c-dddb0819c80f.png)

So it would seem that it is pulling successfully from Firebase - just don't know what I am doing wrong in integrating the short-code in a page then.  

Update #2 >>>>>

I also updated my Authentication settings in Firebase to add the domain. 

![image](https://user-images.githubusercontent.com/48887917/54883486-720d7680-4e3c-11e9-907a-b801122f851c.png)

**Comment by dalenguyen** [comment]
Hi @orbify, this means that you've successfully logged in. You can check by adding this shortcode [firebase_greetings]

**Comment by orbify** [comment]
Thank you so much Dale for your quick response 💯 
Appreciate it!

I tried adding the following pieces of short code to my page:

[firebase_login]  [firebase_greetings]  [/firebase_login]

So while the login "Email" & "Password" shows up - once I enter in my email and my password and hit the "Login" button - nothing further happens.  (I click on the button, and the "Email" and "Password" are still there - and nothing happens on the screen).  

Is there any other back-end configurations I am missing or I should set up?  
My page also has an installed template - could that be interfering?  

Thank you so much Dale! 👍

**Comment by dalenguyen** [comment]
Hi @orbify, 

The [firebase_show]test[/firebase_show] shortcode, will show the custom content, that you have to put in between the shortcode. There're lots of features that I haven't have time to develop yet :D

**Comment by orbify** [comment]
Thank you Dale - this works perfectly 💯  - i.e.:  

[firebase_show] This is a test [/firebase_show]  👍 

If I wanted to display my Realtime Firebase database somehow in Wordpress - do you have any suggestions for how I can accomplish this in Wordpress?  Perhaps use a Table plugin and somehow link that to Firebase query?  Any high-level ideas?  

Really awesome work!  Thank you Dale! (And thank you for your quick replies!)

**Comment by dalenguyen** [comment]
Hi @orbify, I haven't developed the feature to show the database through this plugin yet. If you're interested in, you can create a new request for the new feature and describe the ability of it.

**Comment by dalenguyen** [comment]
@orbify please update to v0.5.2
