### ISSUE TITLE
Firebase Logout

### ISSUE THREAD

**Issue by willm132** [dalenguyen/firebase-wordpress-plugin#160]
**Describe the bug**
When calling [firebase_logout], it asks the user to sign out, then redirects to the wp-login page. This is an issue because the people logging into the website will be customers accessing a database. 

**Expected behavior**
When a customer calls [firebase_logout] it should just refresh the page and have nothing to do with Wordpress login

**Comment by dalenguyen** [comment]
Hi @willm132, which version of the plugin are you using?

**Comment by willm132** [comment]
@dalenguyen I just purchased and installed the plugin today. So I am guessing the most recent.

**Comment by willm132** [comment]
@dalenguyen it is v2.8.0

**Comment by dalenguyen** [comment]
Hi @willm132, you have an option to put a link in order to redirect after logging out. Can you try it and let me know if it works?

```
[firebase_logout redirect="/" button_text="Sign Out"][/firebase_logout]
```

https://firebase-wordpress-docs.readthedocs.io/en/latest/auth/register-login-form.html?highlight=logout#logout-option

**Comment by willm132** [comment]
@dalenguyen Yes! That did work.

**Comment by dalenguyen** [comment]
Awesome. I'm happy to help.
