### ISSUE TITLE
Post Comments & Likes sync at firebase.

### ISSUE THREAD

**Issue by harshachaitanya** [dalenguyen/firebase-wordpress-plugin#161]
**Is your feature request related to a problem? Please describe.**
Currently, we can see only post-related information only. It's better to storage comments, likes on the firebase side. Why because we are unable to show the comments or likes on the mobile app side.

**Which fields does it relate to?**
Firestore

**Comment by dalenguyen** [comment]
It can be done by adding filter hooks before saving data. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/hooks/pro-filters.html#before-saving-post-data-to-firebase
