### ISSUE TITLE
Unable to import users from Firebase firestore.

### ISSUE THREAD

**Issue by harshachaitanya** [dalenguyen/firebase-wordpress-plugin#162]
**Describe the bug**

**To Reproduce**
From the Mobile app, few users signed up. The same user tries into the login web is not happening(vice versa)
From the Web app few users signed up, The same user tries to login into mobile, not happeing(vice versa).

When we try to sync users manually we got the below error.

**Expected behavior**

**Screenshots**
The version of the plugin. E.g PRO v0.5.5

**Screenshots**
![image](https://user-images.githubusercontent.com/35361849/119504791-f1cf5c80-bd89-11eb-83fd-ff49cde248c2.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by dalenguyen** [comment]
Hi @harshachaitanya, 

Is it the first time that you import users? 
What is the current version of the PRO plugin? 

Thanks,

**Comment by harshachaitanya** [comment]
Hi @dalenguyen 

Wordpress 5.7.2
Integrate Firebase PRO 2.11.0
Users 1.1.0
woocommerce : 2.0.0

Thanks,

**Comment by dalenguyen** [comment]
Hi @harshachaitanya, 

Is it the first time that you import users?

Thanks,

**Comment by harshachaitanya** [comment]
Yes @dalenguyen you're correct.

**Comment by dalenguyen** [comment]
If it's the first time you run it, please redeploy cloud functions. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/intro/cloud-functions-deployment.html

**Comment by harshachaitanya** [comment]
Thanks, @dalenguyen after redeployed cloud functions now able to sync the user.

But how can a mobile user log in to the WordPress website?

**Comment by dalenguyen** [comment]
I'm glad that it works. 

Mobile users can sign in via the login shortcode. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/auth/work-with-firebaseui-web.html
