### ISSUE TITLE
Delete categories at firebase firestore side

### ISSUE THREAD

**Issue by harshachaitanya** [dalenguyen/firebase-wordpress-plugin#163]
**Describe the bug**
it's working for creating & update a category at WordPress. But when we delete a category at WordPress it's on delete at firestore side. 

**Expected behavior**
The same category has to delete on firestore side as well.

**Comment by dalenguyen** [comment]
HI @harshachaitanya, it's fixed in v2.11.0. 

It doesn't delete the category on firebase when you delete it on WordPress?

**Comment by harshachaitanya** [comment]
@dalenguyen  yes.

**Comment by harshachaitanya** [comment]
Working in the latest version: 2.11.0.
Thanks @dalenguyen
