### ISSUE TITLE
Register & login in both web & mobile.

### ISSUE THREAD

**Issue by harshachaitanya** [dalenguyen/firebase-wordpress-plugin#165]
@dalenguyen 

On the website, we are using the custom form for user registration & login as below
![image](https://user-images.githubusercontent.com/35361849/120916668-83af6180-c6c8-11eb-82e1-d9b0faa3bcfa.png)
![image](https://user-images.githubusercontent.com/35361849/120916677-8ca03300-c6c8-11eb-8bda-f3cadc2c3713.png)

we are not using 
![image](https://user-images.githubusercontent.com/35361849/120916687-9d50a900-c6c8-11eb-9593-ff98877b5bf8.png)

Consider when a user registers from the web. That user information is storing on the **WordPress database side**. But not at the firebase side.

Consider when a user registers from the mobile. That user information is storing on the **firebase side**. But not on the WordPress database side.

**Requirements:** Irrespective of whether a user registered from Web/Mobile. Users should able to register & login into both Web & Mobile should able to access user information like posts/comments/addresses/orders/user information 
 
Can you suggest to us how to resolve this?

**Comment by dalenguyen** [comment]
Have you tried this to create a login & sign-up page?

https://firebase-wordpress-docs.readthedocs.io/en/latest/auth/register-login-form.html

**Comment by harshachaitanya** [comment]
Yes tried but it's not creating user at WordPress database.

**Comment by dalenguyen** [comment]
@harshachaitanya can you send me the login page with those implementations?

**Comment by harshachaitanya** [comment]
@dalenguyen sorry for the delay.

<form id="firebase-register-form" data-redirect="/" data-send-email-confirmation="true"><div><label for="firstName">First Name</label><input type="text" name="firstName" required=""></div><div><label for="lastName">Last Name</label><input type="text" name="lastName" required=""></div><div><label for="email">E-mail</label><input type="email" name="email" required=""></div><div><label for="phoneNumber">Phone Number</label><input type="text" name="phoneNumber" required=""></div><div><label for="password">Password</label><input type="password" name="password" required=""></div><div><label for="confirmPassword">Confirm Password</label><input type="password" name="confirmPassword" required=""></div><div><button type="submit" id="firebase-register-form__submit" data-ol-has-click-handler="">Register</button></div></form>

**Comment by dalenguyen** [comment]
@harshachaitanya do you have a link for it?

**Comment by harshachaitanya** [comment]
@dalenguyen 
Sorry link means.
if possible can you share the sample code with us.

**Comment by dalenguyen** [comment]
Yes, this is an the demo page for register & login 

https://wordpress.dalenguyen.me/register-login-form/ 

If you have implemented it on your site, you can share a link, so I can help to take a look at it.
