### ISSUE TITLE
Error in console: Firebase is undefined

### ISSUE THREAD

**Issue by Hassankhd** [dalenguyen/firebase-wordpress-plugin#166]
Hello Dale!

I have a couple of things I would like to ask you about. It's important to mention first that I did not use shortcode in any form, instead I used Elementor and made use of the <script> tag and everything worked in my signup and login pages, from Firebase Authentication to Real-time Database.

However, as soon as I redirect the user to the main page after the user logs in, I get an error in the console that reads "firebase is not defined" (I will attach screenshots related to this matter). I really don't know what's wrong because everything looks right, and as I mentioned above, both authentication and the real-time database worked as needed to in the signup and login pages. I will definitely follow up with more comments should you have any questions to further understand the issue I am facing here.

My second question is a bit more general that I was wondering about, and I think it's just a question that someone as moderately experienced as myself would have. Since my website is a multi-page site that has users that stay logged in from the second they log in until they explicitly click on a sign out button that logs them out, I would really appreciate some help with keeping my users logged in until they sign out. I looked it up on Google and I saw many instances where developers use firebase.auth().onAuthStateChanged to fetch the current user's uid and use the uid accordingly to fetch the user's data from the database in question (although no one explicitly stated that this is how we keep users signed in). My second guess is that users are always signed in if the domain is the same, and so there isn't anything I should do to actually keep users signed in since it's done automatically. If keeping users logged in should be done explicitly, I would really love help with how to do so. Thanks in advance!!

<img width="521" alt="Screen Shot 2021-06-08 at 5 11 00 AM" src="https://user-images.githubusercontent.com/72046614/121111641-ef541480-c817-11eb-8833-d23937ad551f.png">

<img width="692" alt="Screen Shot 2021-06-08 at 5 12 39 AM" src="https://user-images.githubusercontent.com/72046614/121111784-29bdb180-c818-11eb-9796-068ee673e8d5.png">

**Comment by dalenguyen** [comment]
Hi @Hassankhd, in order to use a custom script. The script should wait until firebase is loaded. 

I have a template that you can use for adding custom scripts. You can give it a try here. 

https://github.com/dalenguyen/integrate-firebase-template

After downloading the template plugin, you can put your custom script in this file:

https://github.com/dalenguyen/integrate-firebase-template/blob/master/js/firebase-template.js
