### ISSUE TITLE
Integrate Firebase Template issue with pre-existing wordpress plugins

### ISSUE THREAD

**Issue by Hassankhd** [dalenguyen/firebase-wordpress-plugin#168]
Hello Dale!

I remember you suggested that I use the Integrate Firebase Template plugin for my javascript files. I used the plugin to put most of my JavaScript files and tried to load my sign up page but it gave me a weird error in the console about some pre-existing plugins.
<img width="462" alt="Screen Shot 2021-06-18 at 8 37 26 AM" src="https://user-images.githubusercontent.com/72046614/122511757-6c4d6e00-d010-11eb-943b-2b058aed0e68.png">

I contacted wordpress support and they told me the problem is with something related to the plugin and so I had to contact you about it. To help you understand where the issue may be coming from, I will show you one of my sign up files and how I'm adding all my files via  wp_enqueue_script:

<img width="857" alt="Screen Shot 2021-06-18 at 8 40 33 AM" src="https://user-images.githubusercontent.com/72046614/122512170-23e28000-d011-11eb-8031-b5ca00370a72.png">

<img width="1213" alt="Screen Shot 2021-06-18 at 8 41 44 AM" src="https://user-images.githubusercontent.com/72046614/122512099-06151b00-d011-11eb-986e-cf2a9d11a064.png">

the class.if-template.php file is in the "public" folder not the "dashboard" folder. I mentioned this because perhaps it has to be elsewhere and I didn't know. If there's anything else you need to know about let me know. Thanks in advance!!

Best regards,
Hassan

**Comment by dalenguyen** [comment]
Hi Hassan, it's likely that you missing a `")"` in your script. The other errors belong to Jetpack.

**Comment by Hassankhd** [comment]
Hi Dale,

I just fixed the issue as well as most of my errors, but I'm getting this error from the onauthstatechanged function:
<img width="444" alt="Screen Shot 2021-06-20 at 8 49 44 PM" src="https://user-images.githubusercontent.com/72046614/122683772-16dcb100-d20a-11eb-8621-734bc992d850.png">
<img width="462" alt="Screen Shot 2021-06-20 at 8 50 15 PM" src="https://user-images.githubusercontent.com/72046614/122683774-1c39fb80-d20a-11eb-8001-331b05ff2229.png">
Here I'm trying to get the uid of the currently signed in user to perform the vast majority of my firebase functions, but apparently the logged in user is always being undefined, although the sign up/log in process is working and user info is being stored in firebase successfully. Is there anything I'm supposed to add in the sign up/log in pages to guarantee that the onauthstatechanged functions in other pages fetch the logged in user? Please let me know what I can do in this case. Thanks in advance!

**Comment by dalenguyen** [comment]
Can you add this one after the condition? 

```
console.log(user)
```

**Comment by Hassankhd** [comment]
Here's what I got:
<img width="613" alt="Screen Shot 2021-06-20 at 9 57 35 PM" src="https://user-images.githubusercontent.com/72046614/122685181-8e164300-d212-11eb-9ce9-20dbe87a08ae.png">
I can see the user's uid here okay. Should I just write user.uid instead of user.user.uid? I used the latter because I saw something of the sort online as I was learning firebase functions.

**Comment by Hassankhd** [comment]
Hi Dale!

user.uid worked perfectly as you suggested, and I know it did because the sign out sequence worked perfectly for me. However, now I'm having a problem with fetching firebase data. The data is never assigned, and the variables in question (and ultimately the labels) are assigned as undefined. I'm not so sure what's wrong here, so I really need help with this: 

<img width="721" alt="Screen Shot 2021-06-22 at 4 16 55 AM" src="https://user-images.githubusercontent.com/72046614/122848047-7671b400-d311-11eb-894a-7b500c2013c3.png">

<img width="654" alt="Screen Shot 2021-06-22 at 4 17 13 AM" src="https://user-images.githubusercontent.com/72046614/122848053-796ca480-d311-11eb-956c-27872cf1ae6b.png">

I apologize for the many questions, but I know you're always willing to help and I appreciate it as well as all of us users of your awesome plugin!

**Comment by dalenguyen** [comment]
@Hassankhd, sorry I was busy today. I guess you found the solution for it?
