### ISSUE TITLE
Not sync new users when create new user

### ISSUE THREAD

**Issue by Growlyagency** [dalenguyen/firebase-wordpress-plugin#169]
Hi! When we create new user on WordPress, its not syncing it automatic to FireBase. I think that was the point of the plugin. How we get automatic sync to Firebase when make new user on WordPress?

**Comment by dalenguyen** [comment]
Hi @Growlyagency, can you share the current configuration on your dashboard? 

Please make sure that you follow the instruction: https://firebase-wordpress-docs.readthedocs.io/en/latest/firebase/users-to-firebase.html

**Comment by Growlyagency** [comment]
Yes we have followed the instruction. Problem is this: We sell online courses on our WooCommerce store, when customer buy course, account is created automatically after checkout. After customer have purchased course he lands on thanks page. Now when Firebase plugin is active customer redirect automatically from thanks page to homepage and he cant see instructions on landing page. Then he try to log in and Firebase asks First and Last name, email, password again what he have input on checkout so this is little bit hazzle. How we can sync it automatically to firebase after purchase so he dont need to put firstname, lastname,  email and password again for firebase?

**Comment by dalenguyen** [comment]
What about letting the user creates an account before purchasing? WooCommerce has that setting. You don't have to worry about the redirecting to home page after purchasing. And the user will be created once.

**Comment by Growlyagency** [comment]
Hi! I tried that but when i choose Let users create account on checkout it wont show register or login forms. I dont know is that from Learndash because when we sell Learndash courses, it forces to create account in checkout..

**Comment by Growlyagency** [comment]
I think bigger problem is that redirect after purchase, is it possible to disable?

**Comment by Growlyagency** [comment]
Hey. Our sites flow is this, is it right?

Now: User makes order -> Woo makes user -> He logs in first time -> He sync to firebase
I think sync must work like this: User makes order -> Woo makes user -> Synced automatically to firebase without logging in.

How we can achieve that?

**Comment by dalenguyen** [comment]
If Woo makes an account, it will not be synced to Firebase. In the Woocommerce, settings, we shouldn't let users create an account. They have to log in via the plugin in order to continue the purchase flow. 

You can take a look at the sample guide

https://firebase-wordpress-docs.readthedocs.io/en/latest/extensions/woocommerce.html
