### ISSUE TITLE
Automatically redirect from Order Recieved page to Home page after couple of seconds-

### ISSUE THREAD

**Issue by Growlyagency** [dalenguyen/firebase-wordpress-plugin#170]
When customer buy product from our WooCommerce store it redirects customer normally to order recieved page and it works. 

Problem is this: Now when customer are in order recieved page it somehow automatically redirect it to homepage and that is the bug. Is there some function to disable that? In order recieved page there is instructions from product what customer needs to read.
 
So we want to disable the redirect from order recieved page to homepage.

Thanks.

**Comment by dalenguyen** [comment]
Hi @Growlyagency, not sure if it's resolved. I think it relates to WooCommerce configuration.

**Comment by Growlyagency** [comment]
Hei,

Toimistomme on lomalla 05.07 - 26.07. 
Olemme takaisin hommissa alkaen maanantaina 26.07.

Sähköpostiviestisi on tullut perille ja vastaamme siihen palatessamme takaisin hommiin! 🚀

Ystävällisin terveisin,
Santeri Turunen
Toimitusjohtaja
Kasvutoimisto Growly
www.growly.pro

**Comment by Growlyagency** [comment]
Hey! Its not yet resolved. You have any ideas how we can fix it?

**Comment by Growlyagency** [comment]
I think the problem is this:

Normal WooCommerce: When new user makes order it makes account and it logs him automatically in after checkout and he have access to order-recieved page.

With Firebase: When new user makes order it makes account but it wont let him log in automatically because Firebase and then he dont have access to order-recieved page.

**Comment by dalenguyen** [comment]
When applying firebase authentication, the default Woocommerce shouldn't allow users to register via the normal flow. Users should register via the PRO plugin before checking out.

**Comment by Growlyagency** [comment]
Yes they register via the PRO plugin when they log first time in. But how we get that flow like normal WooCommerce? After new customer makes order, he logs automatically in on hes new account?

**Comment by dalenguyen** [comment]
Users should registers before checking out in order to have them on Firebase & Wordpress. 

Users register on firebase mobile app will not automatically sync to WordPress. It will be synced the moment users log in to Wordpress.
