### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by mmw562** [dalenguyen/firebase-wordpress-plugin#172]
Hello Dale!

It appears that the API key, storage bucket, frontend token etc all appear in the url source in the CDATA.  This looks like a big security risk?

**Comment by dalenguyen** [comment]
Hi @mmw562, that information is supposed to be exposed on the front end. 

Please check this one out. 

https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public

**Comment by mmw562** [comment]
That answers it!  Thanks so much!
