### ISSUE TITLE
Firebase Login form not showing

### ISSUE THREAD

**Issue by Growlyagency** [dalenguyen/firebase-wordpress-plugin#174]
Hey, we try to show Firebase UI login form but it wont show it.

I checked css and it says display: none;

#firebase-signout, #firebaseui-auth-container {
    display: none;
}

How we can fix it? I have enabled Allow Login to WP Dashboard -setting.

**Comment by dalenguyen** [comment]
I saw that you closed this. Is it still an issue?

**Comment by Growlyagency** [comment]
I forget to check "Email" checkbox on settings.. Now its working.
