### ISSUE TITLE
User problems after uninstall Firebase Plugin

### ISSUE THREAD

**Issue by Growlyagency** [dalenguyen/firebase-wordpress-plugin#176]
Hi! We have punch of problems after we uninstalled Firebase plugin. Now people cant reset password and if they can, the WordPress not remember new password so it says every time wrong password error.

Where is the problem?

**Comment by dalenguyen** [comment]
Hi @Growlyagency, if the plugin is uninstalled, the issue now is related to WordPress itself. Integrate Firebase plugin doesn't control the authentication process anymore. I'm not sure what happens in this case.
