### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'EmailAuthProvider')

### ISSUE THREAD

**Issue by kiddoapplic** [dalenguyen/firebase-wordpress-plugin#177]
Hi I am trying to integrate woocommerce and working on custom signup form as per given instructions on official docs, but when I open the signup page I am getting below error in console log.  As per video email field doesn't verify and after signup no user is created.  Please provide your valuable feedback, your quick response would be appreciated. Thank you.

![image](https://user-images.githubusercontent.com/86868759/132306417-c170ea8a-313c-4d12-8035-a83d939d9ff9.png)

**Comment by dalenguyen** [comment]
Moved to email communication.

P/s: looks like it's cache / minify related issue.
