### ISSUE TITLE
Unable to view two different tables from the same realtime database at a time

### ISSUE THREAD

**Issue by manoj-kumar-MS** [dalenguyen/firebase-wordpress-plugin#178]
Hi there,
I am using the free version of the Integrate Firebase. When I try to view two tables using two different shortcodes, I am only able to view one of the table. Only the first shortcode is working. Is this a bug or limitation in free version?

Also will I be able to update values to firebase from my website using free version?

**Comment by dalenguyen** [comment]
Hi @manoj-kumar-MS, it's a limitation of the free version. 

You can update value from your website by using a custom script. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/add-custom-scripts.html

**Comment by dalenguyen** [comment]
Closed due to inactivity.
