### ISSUE TITLE
Data not showing up

### ISSUE THREAD

**Issue by jaott1** [dalenguyen/firebase-wordpress-plugin#18]
Hi Dale, I am having issues getting the information pulled in from Firebase and Being able to login. Do you have other instructions that might help me.

**Comment by dalenguyen** [comment]
Can you take a snapshot of you screen and show console log?

**Comment by jaott1** [comment]
![20190525_090817](https://user-images.githubusercontent.com/44622915/58370863-18273c80-7ed1-11e9-9fea-520855c1eea3.jpg)

**Comment by dalenguyen** [comment]
Hi @jaott1, I need more information than this. Such as your configuration, what are you trying to achieve...

**Comment by jaott1** [comment]
Hey Dale, I have a program that is webgl but stored in firebase. The main
site is wordpress. I am needing to have the log in on my wordpress site as
well as keep track of data.
Because right now the user is having to log in to wordpress to get access
to my software but, then log in to the soft ware so that I can track usage.
My main goal is to have one log in for the software.

Jeffrey Ott
Vice President/Creative Design
OTT Theatre Technologies
(936) 443-2291
myvirtualtheatre@gmail.com
www.thevirtualtheatre.com

**Comment by dalenguyen** [comment]
Hi @jaott1, the login between Firebase and WordPress Dashboard is a tricky part. For now, a user can log in, and it will be controlled through Firebase. User cannot see the WordPress Dashboard, but they will have access to Firebase database and firebase's features.

I'm planning to have them integrated into one place, and it's kind of a tricky one to implement.

**Comment by jaott1** [comment]
Ok, so if my user logs in to my game the info will still go to firebase? I am the only one who needs to see dataSent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 5/26/19  2:42 PM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Data not showing up (#18) Hi @jaott1, the login between Firebase and WordPress Dashboard is a tricky part. For now, a user can log in, and it will be controlled through Firebase. User cannot see the WordPress Dashboard, but they will have access to Firebase database and firebase's features.
I'm planning to have them integrated into one place, and it's kind of a tricky one to implement.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ7QNJPLLVGOHW2LIBTPXLR3PA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWIMDKQ#issuecomment-496026026",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ7QNJPLLVGOHW2LIBTPXLR3PA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWIMDKQ#issuecomment-496026026",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
Yes, if your users log in by using the Firebase log in form, they will be managed by Firebase.

**Comment by jaott1** [comment]
Ok cool. Not sure what i am doimg wrong then on the plugin. In my dashboard it will not let me see the database and when i use the code to log in it doesn't do anything Sent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 5/27/19  10:13 AM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Data not showing up (#18) Yes, if your users log in by using the Firebase log in form, they will be managed by Firebase.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ44EXI5UBCJI5HVVKTPXP3BXA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKBG7Q#issuecomment-496243582",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ44EXI5UBCJI5HVVKTPXP3BXA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKBG7Q#issuecomment-496243582",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
Can you send the error from your console when you inspect the browser (Press F12 on Chrome to see the inspection)?

**Comment by jaott1** [comment]
Im not getting an error.  Im not getting anything.  Sent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 5/27/19  10:30 AM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Data not showing up (#18) Can you send the error from your console when you inspect the browser (Press F12 on Chrome to see the inspection)?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQZNAZZXL7APOGMERL3PXP5A3A5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKCI4A#issuecomment-496247920",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQZNAZZXL7APOGMERL3PXP5A3A5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKCI4A#issuecomment-496247920",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
Hi @jaott1, I need to see your configuration and what you are trying to do in your WordPress site in order to figure out what happens. Any pictures would help.

**Comment by jaott1** [comment]
Ok when i get back to my computer i will. Sent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 5/27/19  3:46 PM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Data not showing up (#18) Hi @jaott1, I need to see your configuration and what you are trying to do in your WordPress site in order to figure out what happens. Any pictures would help.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ7RXHBDXJB7JX3CF7LPXRCCLA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKPV6I#issuecomment-496302841",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ7RXHBDXJB7JX3CF7LPXRCCLA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKPV6I#issuecomment-496302841",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jaott1** [comment]
Jeffrey Ott
Vice President/Creative Design
OTT Theatre Technologies
(936) 443-2291
myvirtualtheatre@gmail.com
www.thevirtualtheatre.com

Not sure if this helps or not but, here ya go

**Comment by jaott1** [comment]
I was able to make a test site. It let me bring data from the test site but not from the primary. So i do not know if i am just requesting in the wrong data formSent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 5/27/19  3:46 PM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Data not showing up (#18) Hi @jaott1, I need to see your configuration and what you are trying to do in your WordPress site in order to figure out what happens. Any pictures would help.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ7RXHBDXJB7JX3CF7LPXRCCLA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKPV6I#issuecomment-496302841",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQ7RXHBDXJB7JX3CF7LPXRCCLA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKPV6I#issuecomment-496302841",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
@jaott1 if it doesn't show anything when you get the data, it will show the error in the browser console log when you inspect the site.

**Comment by jaott1** [comment]
It doesn't even show an errorSent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 5/31/19  8:53 AM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] Data not showing up (#18) @jaott1 if it doesn't show anything when you get the data, it will show the error in the browser console log when you inspect the site.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQYGN67HOF6FHZWLOXDPYEUWTA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWVI6DA#issuecomment-497717004",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/18?email_source=notifications\u0026email_token=AKUOIQYGN67HOF6FHZWLOXDPYEUWTA5CNFSM4HPTOZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWVI6DA#issuecomment-497717004",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
Login now supported through FirebaseUI-Web, and database integration is also possible. Read the user guide: https://firebase-wordpress-docs.readthedocs.io/en/latest/index.html
