### ISSUE TITLE
Firebase Accounts aren't automatically synced to Wordpress

### ISSUE THREAD

**Issue by CiriousJoker** [dalenguyen/firebase-wordpress-plugin#180]
**Is your feature request related to a problem? Please describe.**
We have a mobile app (Flutter) and a website (Wordpress).

- User creates a Firebase email+password account in the App
- User tries to log into the website
- Login succeeds (ie it doesn't complain)
- User is still logged out and can't make Woocommerce purchases

**Describe the solution you'd like**
- Creating a new Firebase user should automatically create a properly linked Wordpress account

**Describe alternatives you've considered**
- User could create an account via the website at the expense of terrible UX and a low conversion (ie no way)
- Write a sync cloud function

**Which fields does it relate to?**
Firebase Auth

**Comment by dalenguyen** [comment]
Hi @CiriousJoker, which version of the plugin are you using? 

And do you have a link for the website that I can have a look at?

**Comment by dalenguyen** [comment]
Moved to email support.
