### ISSUE TITLE
Sync existing memberships

### ISSUE THREAD

**Issue by CiriousJoker** [dalenguyen/firebase-wordpress-plugin#184]
**Is your feature request related to a problem? Please describe.**
We have lots of existing memberships. In a future app update, the mechanism to validate those wooCommerce subscription will change to use the new wp_memberships collection in Firestore.

Currently, only memberships that are updated in Woocommerce (ie new memberships & renewed/cancelled ones) will get synced to Firestore.

**Describe the solution you'd like**
We'd like to have a button to import all existing memberships to Firestore.

**Describe alternatives you've considered**
We've looked for a button in Woocommerce to trigger and update to all existing memberships, but we couldn't find such a thing.

**Which fields does it relate to?**
Firestore

**Additional context**

N/A

**Comment by CiriousJoker** [comment]
A few things I've noticed:
- Exporting & importing a membership won't trigger the Firestore sync (changing the exported csv won't change this)
- Manually saving a single membership via the save button will trigger the Firestore sync (this doesn't fix #185 )

**Comment by dalenguyen** [comment]
Hi @CiriousJoker, do you have a bulk `Edit` option in the membership? If you bulk edit, it will trigger the update for all.

![image](https://user-images.githubusercontent.com/14116156/141499324-c8ba88c6-1ebb-4fc7-a42d-a155940db720.png)

**Comment by CiriousJoker** [comment]
This works, thank's. I've only tried with two memberships so far and I can imagine that this still takes quite a lot of time for 60+ pages, but that's something that can be fixed with a lot of work or an autoclicker script. #185 is the bigger issue here, since we can't fix this ourselves.

**Comment by dalenguyen** [comment]
Cool. I will close this one and will check #185 this weekend 👍
