### ISSUE TITLE
Empty userId on synced Woocommerce memberships

### ISSUE THREAD

**Issue by CiriousJoker** [dalenguyen/firebase-wordpress-plugin#185]
**Describe the bug**
- We've imported existing users from Wordpress into Firebase
- When editing an existing user's membership, the `userId` field in the synced Firestore woocommerce membership document is generally empty for the imported accounts.
- In one of the 9 currently synced memberships (rest is missing as per #184 ), the uid is correctly detected as `firstname.lastname`
- Users with a "real" Firebase auth uid, such as `MLVs8g1UR0ab...` (shortened) seem to always get synced correctly
- I can't spot any meaningful and consistent difference between the users where it doesn't work and the one user where it does
- Editing a user's membership will force a resync, but the userId is still unchanged (ie empty or correct depending on the previous state)

**To Reproduce**

I can't really provide reliable steps to reproduce this, maybe this works:

- Deactivate `Integrate Firebase PRO`
- Create a wordpress user manually
- Activate `Integrate Firebase PRO`
- Import all existing users into Firebase
- Attach a new membership to the "old" user

**Expected behavior**

The `userId` field in Firestore should never be empty if there exists a Firebase Auth user

**Screenshots**

![image](https://user-images.githubusercontent.com/16866223/141498741-3357f097-77ef-40aa-b492-bbe600a76050.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

- The current version of the cloud functions is deployed correctly

**Comment by CiriousJoker** [comment]
A couple of things I noticed:
- Editing a non-working user will not trigger a sync to `wp_users/{userId}`, probably because `userId` is unknown/empty. It also doesn't create a new document with a random document id like it usually does when the id is undefined
- Reimporting all users does not change anything

**Also, for context about the collection names:**
![image](https://user-images.githubusercontent.com/16866223/141502020-ff9bbf82-d9ba-4b02-8954-5eed58482581.png)

**Comment by CiriousJoker** [comment]
@dalenguyen 
### Reproduction steps:

1. Create Wordpress account manually
2. Update the user to trigger a sync to `wp_users` (fails, because no `userId`)
3. Import the user into Firebase auth through your import plugin
4. Update the user to trigger a sync to `wp_users` (fails, because no `userId`) <-- This shouldn't happen, after the import the userId field for that wordpress account should be set
5. Log into the wordpress account via FirebaseUI
6. Update the user to trigger a sync to `wp_users` (this works)

**Comment by CiriousJoker** [comment]
@dalenguyen 
I managed to fix it:

Add this snippet into `<plugin>/includes/service/class.firebase-service.php`:

```php
public function import_users_to_firebase($users) {
    ...

    // Set firebase_uid during import
    foreach($users as $user) {
        update_usermeta($user->ID, "firebase_uid", $user->user_login);
    }
    return ...;
}
```

I obviously cannot commit this anywhere, but feel free to include it in the next plugin version.

**Comment by dalenguyen** [comment]
Thanks, @CiriousJoker. It probably what happens. I will add it to the next release 🙌

**Comment by dalenguyen** [comment]
Updated to the plugin 🙏
