### ISSUE TITLE
I'm unable to login, after setting up the firebase database, the user email gets store in the firebase db , but signup is not successful. Guide me on this.

### ISSUE THREAD

**Issue by Gaurav1799** [dalenguyen/firebase-wordpress-plugin#186]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
The version of the plugin. E.g PRO v0.5.5

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**

**Additional context**

**Comment by dalenguyen** [comment]
Hi @Gaurav1799, can you provide more information? 

Version number? 
Sample login link? 
Snapshots?
