### ISSUE TITLE
firebase

### ISSUE THREAD

**Issue by Fitenxd** [dalenguyen/firebase-wordpress-plugin#187]
Hi, I would like to know if I can send the data of people who register on my site to my firebase database through this plugin.

**Comment by dalenguyen** [comment]
Hi @Fitenxd, this feature is not available yet. It does support FCM, however, you have to add a script by yourself in order to make it work. 

If you want to follow the plugin updates, please subscribe to the newsletter here: https://firebase-wordpress-docs.readthedocs.io/en/latest/index.html#
