### ISSUE TITLE
New database 

### ISSUE THREAD

**Issue by stayhomemom240** [dalenguyen/firebase-wordpress-plugin#19]
If I am setting up a new database and new wordpress site with no data available how do I parse the data to the proper collections? There are not setting or documents I found to explain this aspect. Please help

**Comment by dalenguyen** [comment]
Hi @stayhomemom240, are you trying to plan how to organize your database or what?

**Comment by stayhomemom240** [comment]
I guess, I mean how to I tell it what collection to save user data to. like if I was writing the code I would have a component for each collection, how do I tell the data to goto a specific user collection? i.e. chat, payment info, blog, photos, music, etc.

**Comment by dalenguyen** [comment]
I think that will be in a form that you put to the frontend. There'll be different codes that handle different tasks. E.g. In the chat section, we will have codes that handle the chat and put it into the Chats collection...

**Comment by dalenguyen** [comment]
New  user guide: https://firebase-wordpress-docs.readthedocs.io/en/latest/index.html
