### ISSUE TITLE
Sync email from Firebase to Wordpress

### ISSUE THREAD

**Issue by ciriousjoker** [dalenguyen/firebase-wordpress-plugin#191]
**Is your feature request related to a problem? Please describe.**
Changing the user's email in Firebase or Wordpress does not update it on the other service.

**Describe the solution you'd like**
Changing the email in Wordpress should automatically update the email in Firebase.
From Firebase->Wordpress it's not so easy, because Firebase doesn't provider a trigger on user-update.
I've created a Firebase feature request for that, but until that's implemented, it would be great to have this:

- We update users/{uid}.email (<- the document path & field would need to be a variable)
- Your cloud function automatically updates Wordpress accordingly

**Describe alternatives you've considered**
- Not let the user change their email (current solution, not great)
- Deal with Wordpress' api ourselves (currently not worth the effort, also imo this functionality should be offered with this integration)

**Which fields does it relate to?**
Firebase Auth

**Additional context**
N/A

**Comment by dalenguyen** [comment]
Users able to update their email from WP now.
