### ISSUE TITLE
Syncing custom_fields

### ISSUE THREAD

**Issue by ml1970** [dalenguyen/firebase-wordpress-plugin#192]
Syncing posts from WP to Firebase/FirestoreDB with new or updated "custom_fields"... works good (in Firebase-map-format), but if I delete a custom_field in WP the custom_field in firebase will not deleted... Is this a bug or still not implemented?

And second: the comment_count is synced. Is there a way, to sync Comments in WP to Firebase?

**Comment by dalenguyen** [comment]
Hi @ml1970, how does the custom field look on your firestore? Can you send a snapshot? 

How do you delete a custom field in WordPress?

**Comment by ml1970** [comment]
Hi, I'm using your plugin as an bridge between Wordpress and Firestore to use the synced Firestore-documents in an iOS-App. The custom fields storing status informations about the WP-post for usage in the App.  But this is not important for the sync-process - it is only for your information, it is a step long behind the sync-process ;-) 

I save the status informations in different custom fields. When I update the WP-Post and publish it, it will synced correct (Image 1 and 2) - but when I delete the custom field and update the post in WP, the custom field is still in Firestore (Image 3 and 4).

![cf_001](https://user-images.githubusercontent.com/99802533/154913806-be43f7bd-72c3-4fe6-9e42-3eca0451acb7.jpg)
![cf_002](https://user-images.githubusercontent.com/99802533/154913812-5fedd0af-87d4-4170-8350-aa22a127ff0b.jpg)
![cf_003](https://user-images.githubusercontent.com/99802533/154913815-ef4ef367-3086-4497-b221-e303ecde6ccc.jpg)
![cf_004](https://user-images.githubusercontent.com/99802533/154913817-ead1e7f2-7959-4392-8052-6064b499c7c2.jpg)

**Comment by dalenguyen** [comment]
Hi @ml1970, I just update the plugin to v3.5.1. Could you please update it and try if it works? 

Remember to add product key & domain names if you haven't.
https://techcater.com/shop/my-account

https://www.youtube.com/watch?v=ugkE25bAeKw&ab_channel=TechCater

**Comment by ml1970** [comment]
Hi @dalenguyen, thank you for the quick solution. Now it works perfect as expected. Great!

And I had a second question ;-) - is it possible to sync published user-comments from WP to Firebase/Firestore?

Greetings from Germany

**Comment by dalenguyen** [comment]
@ml1970 it may take a while since I have a long list of backlogs. I'll add it to the todo list :D
