### ISSUE TITLE
After integrating Integrate Firebase PRO plugin in my wordpress site getting [Firebase] - This script doesn't belong 

### ISSUE THREAD

**Issue by poojadivedi** [dalenguyen/firebase-wordpress-plugin#193]
**Describe the bug**
After integrating Integrate Firebase PRO plugin in my wordpress site getting [Firebase] - This script doesn't belong 

please help me with this 
![bug](https://user-images.githubusercontent.com/100751370/156313320-27c1916c-985f-47d9-af4e-c2d58460f470.png)

**Comment by dalenguyen** [comment]
Hi @poojadivedi, I got your email. Will move the conversation to email. The issue is the site is installed under a path, not the main domain. I will update the script to support it.

**Comment by poojadivedi** [comment]
Hello Dale Nguyen,

 

Thank you for the quick response yes we are working on the staging site so please update the script really appreciate you for this.

 

Thanks & Regards,
Puja divedi.
