### ISSUE TITLE
Plugin not complete

### ISSUE THREAD

**Issue by Ari0706** [dalenguyen/firebase-wordpress-plugin#196]
Hi, i have seen your tutorial on the plugin, but when i install plugin and enter the API project from firebase to wordpress, it's working fine, just that i don't have all same options in settings that allow me to do more like the tabs : '' Auth, Message, Users, ''  i only have the General tab, Dtabase tab and About tab !
Adding to that i don't see on the wordpress left menu, i have no icon under message to access to the plugin. The only access is threw settings then Firebase and nothing more like yours or any other plugins installed.

Can you please help me out with this !!?

![Capture d’écran 2022-05-18 130629](https://user-images.githubusercontent.com/105811056/169101337-3aba48a9-158a-4f3c-acbc-d2249ce17da4.png)

**Comment by dalenguyen** [comment]
Hi @Ari0706, those features are only available in PRO version. You can click on the PRO version link on the top if you want to get the PRO version.

**Comment by Ari0706** [comment]
oh thanks for the quick support, is there a way to have a free trial for the PRO Version ? just to make sure that it's what i need for my project :)

**Comment by dalenguyen** [comment]
I saw that you talked to the bot. There's a demo site if you want to have a look at the functionality: https://wordpress.dalenguyen.me
