### ISSUE TITLE
interface and user import

### ISSUE THREAD

**Issue by immocalcul** [dalenguyen/firebase-wordpress-plugin#198]
there seems to be a concern for compatibility with wordpress on the plugin and the users load endlessly. 

i use last version wordpress and all plugins
![firebase-integrate-plugin](https://user-images.githubusercontent.com/50158038/181624008-6a9d574b-e050-49cd-bdc3-a6589d554731.jpg)

**Comment by dalenguyen** [comment]
Hi @immocalcul, thanks for your info. Is there any error in the console log when you inspect the browser? 
Can you open the settings tab?

You can send an email to dale@dalenguyen.me, I can help with further support.

**Comment by immocalcul** [comment]
hello dalen i send email and i check the console and return this error:

Failed to load resource: the server responded with a status of 404 () (firebase-admin-js)

**Comment by immocalcul** [comment]
I had to change the access rights in the cpanel to the files is this normal so as not to compromise security : rwx r-- r--

**Comment by dalenguyen** [comment]
Hi @immocalcul, I responded via email. Does it work now after changing the file permission?

**Comment by dalenguyen** [comment]
Issue was resolved.
