### ISSUE TITLE
Shortcodes not working

### ISSUE THREAD

**Issue by TestasoftM** [dalenguyen/firebase-wordpress-plugin#199]
Hello, I purchased and installed Integrate Firebase PRO. I followed the instructions to use the shortcode for the login page but it doesn't display the login or logout buttons. The page is blank. 
Here is the page I set up for the login: https://ucv.testasoft.ro/index.php/logare/

I mention I added all the required firebase credentials as shown in the tutorials.

Please help me figure out why the no login for or logout button is displayed.

Thank you.

**Comment by dalenguyen** [comment]
Hi @TestasoftM, could you please go to https://techcater.com/shop/my-account and add your product key & domain name to your WordPress website? 

![image](https://user-images.githubusercontent.com/14116156/185388676-f09ce107-64b1-4055-a2e0-4682ae0800d0.png)

**Comment by TestasoftM** [comment]
Hello,
I added the domain name to my account on techcater.com. The product's key
is added to plugin's setting.

**Comment by dalenguyen** [comment]
Can you also update the Permalinks link to Post name? 

![image](https://user-images.githubusercontent.com/14116156/185391004-22dfc7d9-b63d-4ce7-ab80-fbf20d417ea2.png)

**Comment by dalenguyen** [comment]
I can see it now.

![image](https://user-images.githubusercontent.com/14116156/185391655-8884164f-49f7-42e9-aeb1-836c5b96e817.png)

**Comment by TestasoftM** [comment]
Done.

**Comment by TestasoftM** [comment]
Now it shows for me also. Thank you.

**Comment by dalenguyen** [comment]
@TestasoftM happy to help! Please also leave a feeback at https://techcater.com/feedback 🙏
