### ISSUE TITLE
Shortcode to display Firestore DB?

### ISSUE THREAD

**Issue by DarkMG73** [dalenguyen/firebase-wordpress-plugin#20]
Hello. I see the Realtime DB shortcode, but nothing to display a Firestore shortcode. I tried changing "Realtime" to "Firestore" on the Realtime hsortcode, but that didn't work. 

I have the Firestore connection set up in the admin, but no way to display it.

Thanks in advance for your help!

**Comment by dalenguyen** [comment]
Database integration is now possible. Read the user guide: https://firebase-wordpress-docs.readthedocs.io/en/latest/index.html
