### ISSUE TITLE
Users data to firebase collection

### ISSUE THREAD

**Issue by TestasoftM** [dalenguyen/firebase-wordpress-plugin#200]
Hello,
can you please help me understand why the users registering via my login page are not saved to my firebase collection "users".
This is my login page: https://ucv.testasoft.ro/conectare
I think I didn't understood very well how to setup this part. If needed I can create an admin account for you to check my settings or provide screenshots.

Thank you!

**Comment by dalenguyen** [comment]
Hi @TestasoftM, have you add the collection name to the settings? You can test by registering a new user. 

If it still doesn't work, you can add me to your testing Firebase & WordPress (dale@dalenguyen.me)

<img width="565" alt="image" src="https://user-images.githubusercontent.com/14116156/187928171-1792c81b-ae1f-40a4-9632-d11130fd5a62.png">

**Comment by TestasoftM** [comment]
Hello,
I created an admin account in wordpress with your email address (user:
Dale) and this password: @b5Llz7Gyz)PXB9orRu
I also added you as editor to the firebase.

Please let me know if you need any other acces.
Thank you!

**Comment by dalenguyen** [comment]
Thanks, @TestasoftM. You can send the passport to my email. This is a public page. Putting the passport here is not secure. I removed it for you.

**Comment by dalenguyen** [comment]
Resolved.
