### ISSUE TITLE
Account details fields missing

### ISSUE THREAD

**Issue by TestasoftM** [dalenguyen/firebase-wordpress-plugin#201]
Hi Dale,
It seems that the Firebase PRO plugin prevents some fields from the account details to be displayed in the my account page. Is the e-mail and change password fields.
How can I solve this?
Thank you.

**Comment by TestasoftM** [comment]
Thank you for your answer. In this case, how can users that login via
mobile phone can also add an email address to their account?
Is this possible?

**Comment by dalenguyen** [comment]
At the moment, when they purchase something, they can add their email at the checkout step. I'm working on supporting updating email feature.
