### ISSUE TITLE
Unable to logged in after order

### ISSUE THREAD

**Issue by AbdurrahmanSimsek** [dalenguyen/firebase-wordpress-plugin#203]
I am using Create New User at Checkout feature. It does not redirect the customer to the my account page when the payment process is completed. It automatically logs out and redirects to the log in page.

**Comment by dalenguyen** [comment]
Hi @AbdurrahmanSimsek, could you please check https://techcater.com/shop/my-account

And download the latest versions of both plugins. It should be 3.23.1 for PRO and 2.16.0 for Woocommerce.

**Comment by AbdurrahmanSimsek** [comment]
> 

Hi, i uploaded latest versions. But still the same error persists.  It does not redirect the customer to the my account page when the payment process is completed. It automatically logs out and redirects to the log in page.

**Comment by dalenguyen** [comment]
Hi @AbdurrahmanSimsek, can you send a test link to my email? I can help to take a look at it.

dale@dalenguyen.me

**Comment by dalenguyen** [comment]
Solved.
