### ISSUE TITLE
Missing Fields on Subscription Document!!

### ISSUE THREAD

**Issue by malachi-padilla** [dalenguyen/firebase-wordpress-plugin#204]
**Subscription Items & Line Items not syncing to firestore**
When a subscription is placed in WooCommercr it pushes that data to firestore. Now, all the data is coming over except the "items" & "line items" fields. These are the only fields linking a subscription to a product.  Very important! There is a workaround by using the parentID for the order and getting all the info that way, but it would be nice to have that data already in the subscription document.

**To Reproduce**
1. Create a subscription product in Woo
2. Purchase subscription
3. Notice missing fields

**Expected behavior**
We expected to see those fields populated, with information about which products a user subscribes to. 

The version of the plugin. E.g PRO (v3.25.0)

**Comment by dalenguyen** [comment]
Hi @malachi-padilla, do you know which version of the WooComerce extension you're using?

**Comment by dalenguyen** [comment]
Close due to inactivity.
