### ISSUE TITLE
Import Wordpress Users to Firebase

### ISSUE THREAD

**Issue by fireflysystems** [dalenguyen/firebase-wordpress-plugin#209]
**Describe the bug**
I purchased the product because of this story you posted. I am trying to import my wordpress users to firebase, but im unable to figure out how. Please Guide me. 

https://medium.com/@TechCater/import-wordpress-users-into-firebase-authentication-463b23649322

**Comment by dalenguyen** [comment]
Hi @fireflysystems, you need the PRO plugin & Users extension in order to import users from WP to Firebase. Please check the docs at: https://firebase-wordpress-docs.readthedocs.io/en/latest/extensions/firebase-users.html

**Comment by dalenguyen** [comment]
Close due to inactivity.
