### ISSUE TITLE
Enable use of custom claims

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#21]
Haven't tried the plugin yet, but trying to evaluate the features.

Is there a way to enable use of custom claims from Firebase rather than relying on a database for user metadata?  We already use custom claims for our website by checking if logged in users have a certain claim.

Would be ideal to have this plugin check if a logged in user has a certain claim in order to manage access.  Is that possible?

For reference:  https://firebase.google.com/docs/auth/admin/custom-claims

**Comment by dalenguyen** [comment]
Thanks Joseph for your support. Custom claims can be managed through custom shortcode and JavaScript. 

Here is an example of writing a custom shortcode to display data from Firestore

https://dalenguyen.me/blog/how-to-retrieve-data-from-firestore-and-display-on-wordpress-abj?id=199634

It will be the same with custom claims. I'm away for a week and will write a tutorial to show how to manage it when I come back.

**Comment by nasajoey** [comment]
Thanks for the response.  Look forward to the tutorial.

**Comment by dalenguyen** [comment]
Hi @nasajoey, please check this tutorial for custom claims: https://dalenguyen.me/blog/how-to-work-with-firebase-custom-claims-in-wordpress-4913?id=211659

**Comment by nasajoey** [comment]
Thanks... I think it makes sense, but still digesting it.  Haven't tried yet.

**Comment by dalenguyen** [comment]
@nasajoey when you have time give it a try. I already tested in local. And please update the plugin to v0.5.4 :D
