### ISSUE TITLE
User not marked as logged in

### ISSUE THREAD

**Issue by gina108** [dalenguyen/firebase-wordpress-plugin#210]
When a new user logs in with google (using Integrate Pro social login) the user is created in Firestore and in Wordpress but the user does not get routed to logged in page, and cannot see pages visible to logged in users.  

It appears that the user gets created in the databases but not marked as logged in.

I added a button from nextend social login at the bottom and the user will stay logged in that way.

**To Reproduce**
1. go to www.fluentzkidz.com 
2.  click on login.
3. log in with google.

Nothing will happen. Then when you try to access other pages it will show the button for nextend social log in and that button will log the user in fine.

I added the Nextend butter after the problem occurred. The problem isn't occurring because of the button. 

**Expected behavior**

I expect to be logged into profile page, or at least have access to account page after logging in with google.

I am trying to integrate with stripe also.

Integrate Firebase PRO (v3.32.0)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**
 - Windows
 - Chrome

I can log in with the Nextend Social Login button, but not with the Integrate Pro buttons. I haven't configured the apps for windows or facebook yet. But google should be good to go,

**Comment by dalenguyen** [comment]
Hi @gina108, 

Can you check if you followed these guides correctly? 

https://firebase-wordpress-docs.readthedocs.io/en/latest/intro/cloud-functions-deployment.html

https://firebase-wordpress-docs.readthedocs.io/en/latest/auth/wordpress-user-integration.html

Please make sure that you check the box: Allow Login to WP Dashboard, so it can allow users to log in to both WP & Firebase. 

![image](https://github.com/dalenguyen/firebase-wordpress-plugin/assets/14116156/5ff3c951-d7c8-4685-bc4e-762cdfb915d7)

**Comment by dalenguyen** [comment]
Close due to inactivity.
