### ISSUE TITLE
Google Analytics (GA4) key events tracking

### ISSUE THREAD

**Issue by igornes** [dalenguyen/firebase-wordpress-plugin#212]
We use Firebase Pro for sign-up and sign-in. It is important to track new sign-up events in Google Analytics GA4. Google Ads uses those events for conversion tracking. The tracking feature should allow the use of GA4 IDs to track events in Google Analytics.

**Comment by dalenguyen** [comment]
Hi @igornes, how do you trigger the tracking event? Are there any methods that you're using for it?

For the authentication, which shortcode are you using for sign-up and sign-in?

**Comment by dalenguyen** [comment]
Close due to inactivity.
