### ISSUE TITLE
Get data from firebase realtime database without login

### ISSUE THREAD

**Issue by vikasawasthi093** [dalenguyen/firebase-wordpress-plugin#213]
How to Get data from Firebase real-time database without login ?
![Screenshot 2024-08-18 000319](https://github.com/user-attachments/assets/b037359d-17fe-46fd-8043-e453e6f770c4)
- like if i want to get playerscores of Player 1

**Comment by dalenguyen** [comment]
Hi @vikasawasthi093, you will likely need custom javascript code for this. 

https://firebase.google.com/docs/database/web/read-and-write 

And the security rules that allow anyone can read `playerscores`.

**Comment by vikasawasthi093** [comment]
> Hi @vikasawasthi093, you will likely need custom javascript code for this.
> 
> https://firebase.google.com/docs/database/web/read-and-write
> 
> And the security rules that allow anyone can read `playerscores`.

can you please create a demo code for me, because i am new in web development , please create a single demo script , if you then i can pay some money also like 2000

**Comment by dalenguyen** [comment]
You don't need to pay 2000. You can get an hour support at https://techcater.com/shop/products
