### ISSUE TITLE
Getting warnings in Admin 

### ISSUE THREAD

**Issue by SenexTech** [dalenguyen/firebase-wordpress-plugin#214]
Hi, Getting these warnings in Admin on free version:

Warning: Trying to access array offset on value of type bool in /home/lciifz88/public_html/wp-content/plugins/integrate-firebase/includes/class.firebase-admin.php on line 56

Warning: Trying to access array offset on value of type bool in /home/lciifz88/public_html/wp-content/plugins/integrate-firebase/includes/class.firebase-admin.php on line 57

Warning: Trying to access array offset on value of type bool in /home/lciifz88/public_html/wp-content/plugins/integrate-firebase/includes/class.firebase-admin.php on line 61

Warning: Trying to access array offset on value of type bool in /home/lciifz88/public_html/wp-content/plugins/integrate-firebase/includes/class.firebase-admin.php on line 62

Warning: Trying to access array offset on value of type bool in /home/lciifz88/public_html/wp-content/plugins/integrate-firebase/includes/class.firebase-admin.php on line 63

Warning: Trying to access array offset on value of type bool in /home/lciifz88/public_html/wp-content/plugins/integrate-firebase/includes/class.firebase-admin.php on line 64

PHP version | 8.1.30 (Supports 64bit values)
WP Version | 6.7
Site Language | en_US
User Language | en_US
Timezone | +00:00
Permalink structure | /%postname%/
Is this site using HTTPS? | Yes
Is this a multisite? | No
Can anyone register on this site? | No
Is this site discouraging search engines? | No
Default comment status | Open
Environment type | production

**Comment by dalenguyen** [comment]
Hi @SenexTech, it's warnings. Does it affect your site?

**Comment by dalenguyen** [comment]
Thanks for reporting. If you have any other requests, please let me know.

**Comment by dalenguyen** [comment]
Thanks, @SenexTech. This is fixed in v0.10.0
