### ISSUE TITLE
Consider use of FirebaseUI for login?

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#23]
For UX/UI consistency it would be neat to have the option of FirebaseUI login: 

https://github.com/firebase/firebaseui-web

We use this on our main site, so it would be nice to have a similar look and feel for login.  It is recommended in the Firebase docs as well (https://firebase.google.com/docs/auth/web/firebaseui).

My guess is that you'd have a button instead of the "E-mail" and "Password" form currently implemented.  And that button would pop up the "standard" login window provided by the FirebaseUI library.  I think this would open the door to allowing smoother login via other providers if one's Firebase auth was configured to do so.

I'm unsure of the level of effort to add this option, but hoping you might consider it!

**Comment by SebastianBO** [comment]
Great idea, same here.

**Comment by dalenguyen** [comment]
@nasajoey @SebastianBO Yup, it sounds like a great idea.

**Comment by nasajoey** [comment]
If we were in a measuring mood... HOW great of an idea is it?  With "1" being "Great, but won't ever do it."  And "10" being "Soooooo great that I'm working on it now and will have it done tomorrow!"

Just curious if I should be spending time trying to improve the UI for the current plugin for our site or just wait for this awesome improvement.

Thanks in advance for any insights!

**Comment by dalenguyen** [comment]
Hi @nasajoey, I would say it about 8. I will start working on it this weekend. Hopefully, it can be released in the next two or three weeks.

**Comment by dalenguyen** [comment]
Hi @nasajoey, which kind of authentications that you are using now?

**Comment by nasajoey** [comment]
We actually only use email auth for now, but are hoping to activate Google and Twitter in the near future.  If you got just the email auth part going now, that would be super great for me personally.  Really more about the unified look and feel provided by firebaseui-web for us.

**Comment by dalenguyen** [comment]
@SebastianBO @nasajoey the integration is done. There are options that you can enable email, google, twitter, facebook... I need to update the document and the site. Everything should be done this weekend.

**Comment by nasajoey** [comment]
Great!  A merry Christmas indeed!  Will be happy to test this out soon after you have it available.

**Comment by dalenguyen** [comment]
It's finally out!!! Please go to [https://firebase.dalenguyen.me](https://firebase.dalenguyen.me) to download the version 0.5.5. 

User guide: https://firebase-wordpress-docs.readthedocs.io/en/latest/work-with-firebaseui-web.html

**Comment by nasajoey** [comment]
Awesome!  Looking forward to trying.  

Trying to download and having problems that I haven't had before with your site.  The "Download" button takes me to the /download page and there is another link "Integrate Firbase PRO" but its target is just "https://firebase.dalenguyen.me/" and nothing gets downloaded.

**Comment by dalenguyen** [comment]
@nasajoey it fixed now. Please try it again.

**Comment by nasajoey** [comment]
Download now works.  Thanks.
