### ISSUE TITLE
Firebaseui redirect URL, possible to default to current page?

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#24]
We will have the login present as a gate for users to access everything beyond the beginning of a post.  So the login will be on every post for not-logged-in users.  In order for such a scheme to work with Firebaseui-web, the redirect on successful login would need to come back to the current page, not a general redirect.

Is this possible for me to configure in the current version or would it be a new feature?

**Comment by dalenguyen** [comment]
This is not supported now. It should be a new feature or custom customization.

**Comment by dalenguyen** [comment]
@nasajoey it is implemented. https://firebase-wordpress-docs.readthedocs.io/en/latest/work-with-firebaseui-web.html
