### ISSUE TITLE
Impossible to download the PRO Plugin

### ISSUE THREAD

**Issue by brettmac99** [dalenguyen/firebase-wordpress-plugin#27]
Hey guys, I just bought the PRO version and could not download the plugin.

**Comment by brettmac99** [comment]
<img width="662" alt="Screen Shot 2020-02-27 at 10 28 08 pm" src="https://user-images.githubusercontent.com/61544411/75440851-a4aae200-59b0-11ea-9c85-80d7493d9aac.png">

Download link not working, after paying for it.

**Comment by dalenguyen** [comment]
Thanks @brettmac99 for you support. I fixed the download link. Please try it again.
