### ISSUE TITLE
Nice to have JS error to GUI

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#28]
Very minor request/suggestion for a future release.

**Is your feature request related to a problem? Please describe.**
When setting up the new version of the plugin, I set the project settings in "General", then navigate to "Users."  A button is presented to "Click to load users."  I clicked it and waited.  Clicked again.  Didn't know if there was an error or latency.  There was no feedback in the GUI to indicate what might be happening.  I opened the JS dev console and saw a helpful message about finishing setup in "Settings" tab.

**Describe the solution you'd like**
Would suggest sending that helpful console message (forget the exact words now, but something to the effect of finishing setup first in the "Settings" tab) to the GUI to reduce confusion.

**Additional context**
Happy to clarify if needed.

**Comment by dalenguyen** [comment]
Thanks, @nasajoey. This is definitely a great suggestion. I will add this to the next release which is this week!

**Comment by dalenguyen** [comment]
Hi @nasajoey, it's updated in version 0.11.1.
