### ISSUE TITLE
User Search

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#29]
**Is your feature request related to a problem? Please describe.**
When clicking "Click to load users" in the "Users" tab, I get a full list of all of our users.  However, that list is 100's of folks long.  They only way to find a particular user is via using the browser to search the page.  Unless I am missing a filter feature?

**Describe the solution you'd like**
I'd like a way to filter users or search for a particular user.

**Describe alternatives you've considered**
Searching the full list of users via browser command-F is all I seem to be able to do currently.

**Which fields does it relate to?**
Firebase Auth tab

**Additional context**
Would like to use this for the business folks to be able to manage claims so that I don't have to run a standalone program to do that updating.  This search feature would be vital for that.

Happy to provide more details as needed.

**Comment by nasajoey** [comment]
Could be a separate issue or just related to this one:  would probably be good to have a start/offset/pagination by default for listing users.

**Comment by dalenguyen** [comment]
Thanks @nasajoey, the second one is more complicated than the search feature. It should be on a separate ticket.

**Comment by nasajoey** [comment]
Makes sense... the first one is more important anyway to my use cases.  Thanks for taking a look!

**Comment by nasajoey** [comment]
Ugh... now based on Issue #30 definitely need the filter feature else I can't load all of our users.  Thanks again for the help with this!

**Comment by dalenguyen** [comment]
Hi @nasajoey, I added the search / filter in version 0.12.0. Looks like you have more than 1000 users. It will be added in the next release.
