### ISSUE TITLE
Problem with login form

### ISSUE THREAD

**Issue by liritf** [dalenguyen/firebase-wordpress-plugin#3]
I downloaded and activated "Integrate Firebase" plugin and created a WordPress page with [firebase_login] as a shortcode. The form states to enter name and email, but the name field expects @ sign. However, when entering my Firebase email and password, I am unable to login. The screenshot is below. What might be the problem? Also, after logging in, should I be seeing real-time database as if I was logged into Firebase?
Thank you!
![loginform](https://user-images.githubusercontent.com/41241466/42729500-eedff462-879f-11e8-859a-1f6cc75527a6.png)

**Comment by dalenguyen** [comment]
Hi @liritf, can you show the console log error from your browser?

**Comment by liritf** [comment]
Hi @dalenguyen, is this what you meant?
I double checked the API key and it should be correct, yet logging in still does not work.

![error](https://user-images.githubusercontent.com/41241466/42850411-1763bf96-89ed-11e8-8986-a067925cd14c.png)

**Comment by dalenguyen** [comment]
Yes, this is the API key issue. Can you take a snapshot of your configuration & your firebase configuration? Remember to censor half of your credentials.

**Comment by dalenguyen** [comment]
Hi @liritf , I just updated the version of the plugin to v0.3.1. Please update and try it again. Thanks,

**Comment by liritf** [comment]
Below is the screenshot of the firebase credentials. I updated the plugin to the newest version (0.4.0), and now I am getting another error message, the screenshot is also below. I enabled email sign-in in firebase authentication. I am able to use the email and password to sign in to firebase directly, but not through the plugin.
![cred](https://user-images.githubusercontent.com/41241466/42920700-b0285cbe-8add-11e8-9239-f57813a4e123.png)
![error](https://user-images.githubusercontent.com/41241466/42920706-b4c8a17a-8add-11e8-9d2c-1abfcb5d4d15.png)

**Comment by dalenguyen** [comment]
Hi @liritf, please check if you have that user in the firebase authentication. You can take a snapshot of the user if it's possible.

**Comment by liritf** [comment]
Hi @dalenguyen, the problem was in the Firebase authentication. Now the login works, thank you! Just another quick question: in the shortcode to show data to the user, what class name is it referring to?

**Comment by dalenguyen** [comment]
Hi @liritf, it's for you to decide and style it. 

`echo do_shortcode("[firebase_show class='**your-class-name**']YOUR HTML CODE[/firebase_show]");`
