### ISSUE TITLE
1000 limit on viewing users

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#30]
**Describe the bug**
Users tab can only load up to 1000 users

**To Reproduce**
1. Have 1000+ users in firebase auth
2. Click on 'load users' in Users tab of plugin GUI
3. Search for the word "Delete" and see there are 1000 results (one per row/user)
4. See that all of your users are not loaded.

**Expected behavior**
Some method to see all users, perhaps paginate results, perhaps a filter (see other issue)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**
 - OS: OSX 10.15.2
 - Browser Chrome 79.0.3945.130
 - Version 11.0

**Additional context**
We have roughly 1400 users in Firebase.  Found this bug as I searched the Users page for a particular user after loading and couldn't find.  Happy to follow up as needed.

**Comment by dalenguyen** [comment]
Hi @nasajoey, the limit is removed in version 0.13.0. Please give it a try.
