### ISSUE TITLE
Deleting all claims seems to be an invalid operation?

### ISSUE THREAD

**Issue by nasajoey** [dalenguyen/firebase-wordpress-plugin#31]
**Describe the bug**
Not able to fully delete a custom claim

**To Reproduce**
1. Go to users tab
2. Find a user with an existing custom claim
3. Click edit, delete the text in the claim box.  Click Save
4. Reload the page and user db, you will see that the claim is still present with the user.

**Expected behavior**
I expected the claim box to be empty due to deleting the content and saving the user before refreshing the page.

**Additional context**
I found that was able to successfully change the claim to 'false' and save it and reload to see the change.  I'm assuming this is the preferred approach by the plugin.  Some feedback to the user would be useful if this is the case.  For example either not allowing the text to be deleted or indicating that removing the array of claims is not allowed when trying to click save.  And maybe a suggestion to change to false instead.

I may make a separate feature request to get a more GUI-focused way to change existing claims (a checkbox or something).

**Comment by dalenguyen** [comment]
This is fixed in v0.14.0, and remember to redeploy the cloud functions.
