### ISSUE TITLE
FrontEnd User Profile Maker

### ISSUE THREAD

**Issue by jaott1** [dalenguyen/firebase-wordpress-plugin#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I would like the user to be able to create there own profile and log in. This way the user can purchase my product to create an account and use it as needed. I would prefer not having to let all users into my dashboard to create an acct. 

**Describe alternatives you've considered**

**Additional context**

**Comment by dalenguyen** [comment]
Hi @jaott1, which version of the plugin are you using? 

And your product is in Firebase database or WordPress (WooCommerce) for example?

**Comment by jaott1** [comment]
I have the 0.14 version. Firebase databaseSent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 4/20/20  7:49 PM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] FrontEnd User Profile Maker (#32) 
Hi @jaott1, which version of the plugin are you using?
And your product is in Firebase database or WordPress (WooCommerce) for example?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/32#issuecomment-616884559",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/32#issuecomment-616884559",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
Hi @jaott1, the current stage of the plugin allows users to register or login with their Firebase credentials on the WordPress website. 

It is what you want? 

Documentation: https://firebase-wordpress-docs.readthedocs.io/en/latest/work-with-firebaseui-web.html

**Comment by jaott1** [comment]
Yes. Sent from my Sprint Samsung Galaxy S9.
-------- Original message --------From: Dale Nguyen <notifications@github.com> Date: 4/20/20  10:01 PM  (GMT-06:00) To: dalenguyen/firebase-wordpress-plugin <firebase-wordpress-plugin@noreply.github.com> Cc: jaott1 <myvirtualtheatre@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dalenguyen/firebase-wordpress-plugin] FrontEnd User Profile Maker (#32) 
Hi @jaott1, the current stage of the plugin allows users to register or login with their Firebase credentials on the WordPress website.
It is what you want?
Documentation: https://firebase-wordpress-docs.readthedocs.io/en/latest/work-with-firebaseui-web.html

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/32#issuecomment-616922716",
"url": "https://github.com/dalenguyen/firebase-wordpress-plugin/issues/32#issuecomment-616922716",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dalenguyen** [comment]
Firebase User Account available in v1.0.0
