### ISSUE TITLE
How can I call a Cloudfirestore?

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#33]
**This is not a bug**
When a read the documentation, I saw this shortcode [realtime class='your-class-name' collection_name='Users' document_name='string']
And I dont know how to use....

Can you put a example of a cloud firestore call ~users~ ?

**To Reproduce**

**Expected behavior**

**Screenshots**
The version of the plugin. E.g PRO v0.5.5

**Screenshots**
If applicable, add screenshots to help explain your problem. You can find the error code from inspecting the browser.

**Desktop (please complete the following information):**

**Additional context**

**Comment by dalenguyen** [comment]
Hi @mcollinar, here is an example that you can look at 

https://wordpress.dalenguyen.me/display-realtime-document-data/

For example, here is my realtime structure

![image](https://user-images.githubusercontent.com/14116156/80629783-530aec00-8a21-11ea-9c5c-c9000af96468.png)

That means this is the shortcode that I will put on WordPress inside a Post / Page:

```
[realtime class='your-class-name' collection_name='cars' document_name='2dd75620-89be-11ea-97ce-5f05b4f33912']
```

If you don't know how to put the shortcode in WordPress, you can take a look that this video: https://youtu.be/zToMwKsAdwA?t=454
