### ISSUE TITLE
create a My account page to add or change information

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#35]
**Is your feature request related to a problem? Please describe.**
I`m trying to create a My account page, but I cannot integrate the logged users with the Users collection.

For example, the user that are trying to log in is hHmTfzqCcgTbMChH2K2dF8AoYES2

and when this user logged in, I want to him see the information that are in this shortcode: 
[firestore class='your-class-name' collection_name='Users' document_name='string']
How can I do this?

**Describe the solution you'd like**
[firestore class='your-class-name' collection_name='Users' document_name='current_uid' document_uid='id']

When:
- document_name='current_uid' --- the UID that is logged in
- document_uid='id' --- the locations of UID in the collections name 'Users'

**Describe alternatives you've considered**

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

**Additional context**

**Comment by dalenguyen** [comment]
It will be added in v1.0.0
