### ISSUE TITLE
Make possible to get just a few informations in a collectio for a document

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#36]
**Is your feature request related to a problem? Please describe.**
How can I get just one information of a collection? For example: in the collection Users, I just want to bring the Photo... Is it possible to do that?

**Describe the solution you'd like**
I`m talking to something like this: [firestore class='your-class-name' collection_name='Users' display_fields='foto' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2']

When "Display_information" is the name of informations that we have in a collection... could be more than one

**Describe alternatives you've considered**

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

**Additional context**

**Comment by dalenguyen** [comment]
You have an option to add display fields to a document in v0.18.0 now.
