### ISSUE TITLE
Sign In Success Url not working

### ISSUE THREAD

**Issue by elmcapp** [dalenguyen/firebase-wordpress-plugin#38]
I have pro version of the plugin.
1. I have set Sign In Success Url to /accounts  
2. When someone go to the login page  /login then they put in their login information and press submit they are logged in successful however the plugin redirects them back to the current page just without the login form. They are able to see content for login users however they are not being redirected. to /accounts

**Comment by elmcapp** [comment]
![plugin](https://user-images.githubusercontent.com/64275658/81355283-00be7080-909c-11ea-802d-17763292ab8a.png)

**Comment by dalenguyen** [comment]
Thanks @elmcapp. I’ll check this bug and will back to you this weekend. 

Meanwhile can you create a video / gif of what is happening on the site and send it to me? 

You can send it to dale@dalenguyen.me 

Thanks,

**Comment by elmcapp** [comment]
Here is a video link of the bug
https://drive.google.com/open?id=18TLCjtXunQWJ49v2sAqQh07vbtnw9rTv

**Comment by elmcapp** [comment]
Do we have a fix for this bug?

**Comment by dalenguyen** [comment]
Yes, the fix will be released tomorrow.

**Comment by dalenguyen** [comment]
This is fixed in v0.18.0

**Comment by elmcapp** [comment]
Can you also add a redirect for users already logged in. Meaning if a users has not logged out and they go to the login page it will redirect them?

**Comment by dalenguyen** [comment]
Hi @elmcapp, can you send me the snapshot of your current implementation? It's the login page after logging in.
