### ISSUE TITLE
Download firestore database with this plugin?

### ISSUE THREAD

**Issue by omurbekjk** [dalenguyen/firebase-wordpress-plugin#4]
Just an idea, it will be nice to download firestore database as json in wordpress backend and convert it to excel or csv format and send to the user to download file.

**Comment by dalenguyen** [comment]
Hi @omurbekjk, this feature will be added to the next update. Please watch for changes :)

**Comment by dalenguyen** [comment]
Hi @omurbekjk, Firestore is supported in version [0.4.0](https://srd.wordpress.org/plugins/integrate-firebase/)

**Comment by omurbekjk** [comment]
Hi @dalenguyen good job! Can I install this plugin and download my firestore data from wordpress as an excel file?

**Comment by dalenguyen** [comment]
Hi @omurbekjk , you can get the JSON from the dashboard. JSON structure is kind of complicated to turn it into an excel file because it has many levels. It depends on how you want to use it. You can get the JSON and turn it into whatever you want.

**Comment by omurbekjk** [comment]
@dalenguyen yes, firebase supports downloading whole db as json file. My requirement was to download it as excel file, and I was thinking to use wordpress to convert it to excel.

**Comment by dalenguyen** [comment]
Hi @omurbekjk, just to confirm. Firebase Firestore allows you to download the whole DB as a JSON file?
