### ISSUE TITLE
Any way to customize the UI

### ISSUE THREAD

**Issue by elmcapp** [dalenguyen/firebase-wordpress-plugin#40]
The Firebase Frontend UI is nice but is there any way  to customize it. I need to add some extra labels in the form. Basically where it show Sign in with email, I would like to have an H3 tag above that with some custom text

**Comment by dalenguyen** [comment]
Hi @elmcapp, you can add a custom text above the login shortcode. It will show you the text and the form. Is it what you want?

**Comment by elmcapp** [comment]
I was hoping to get the text to show inside of the form. I figured it out. I had to download the jquery code to server and edit the text there
