### ISSUE TITLE
Integratiuon with WPBakery Page Builder

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#41]
**Is your feature request related to a problem? Please describe.**
Put all the shortcode available in the WPBakery Page Builder

**Describe the solution you'd like**
Just put all the shortcode in the plugin, just like woocomerce or dokan did...

**Describe alternatives you've considered**

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

**Additional context**

**Comment by dalenguyen** [comment]
Can you explain more? Shortcode does work in WP Bakery. http://superstorefinder.net/support/knowledgebase/add-shortcode-wp-bakery-builder-visual-composer/

**Comment by mcollinar** [comment]
the shortcode works fine in the plugin...but i thought in something else. just like woocommerce did, or example....

**Comment by mcollinar** [comment]
![Captura de Tela 2020-05-15 às 22 12 48](https://user-images.githubusercontent.com/35809337/82106802-b66f6c00-96f9-11ea-9443-3a5f924cb590.png)
![Captura de Tela 2020-05-15 às 22 12 10](https://user-images.githubusercontent.com/35809337/82106806-bcfde380-96f9-11ea-82aa-05e463032061.png)
for example this....

**Comment by dalenguyen** [comment]
This is an extra feature that is not suitable for the current development progress. Let bring up this one in the future.
