### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by elmcapp** [dalenguyen/firebase-wordpress-plugin#43]
Issues with logout. Using the shortcode you provide to logout works to sign you out of firebase and wordpress. HOWEVER: if you use a plugin to hide the admin bar, the shortcode you provide will provide a logout button and it will log you out of firebase however it does not log you out of wordpress

**Comment by dalenguyen** [comment]
Thanks @elmcapp, I will take a good look at an alternative solution. If you encounter any solutions, please let me know. I wonder how users log out if they don't see the log out button without the admin bar.

**Comment by elmcapp** [comment]
Where you able to find out the issue with not being able to logout of wordpress. Your plugin will logout from firebase however the wordpress user is still logged in.

**Comment by dalenguyen** [comment]
@elmcapp Not yet, I will try some additional methods this weekend.

**Comment by dalenguyen** [comment]
Fixed in v0.20.0
