### ISSUE TITLE
Create new user in Firebase

### ISSUE THREAD

**Issue by elmcapp** [dalenguyen/firebase-wordpress-plugin#44]
Your plugin has a feature where on the backend we can add a new user. I have membership plugin where members need to be created in the wordpress database first. Can you add the feature where when a user create an account directly in wordpress then for that current user it will create an account for them in firebase

**Comment by dalenguyen** [comment]
Hi @elmcapp, which plugin is it, and how is the user created with the plugin? Thanks,

**Comment by elmcapp** [comment]
ARMember is the plugin. The plugin just use users that are already in the wordpress database. 
Basically I was hoping that in the admin panel you could have an options that say: "create users from wordpress database"

Anyone that register on the wordpress website using the wordpress login and registration form it will  create new user account in firebase. If that's not easy maybe have a cronjob that can search the wordpress db for wordpress users and sync those users to firebase. 

Basically you already have a section in your plugin that allow us to create new users. All me need now is to allow that to work for visitors of a wordpress site that want's to register using the default wordpress login and registration from. 

By doing this you will provide your plugin users the option to use the plugin in the way you intended which is to allow syncing firebase users with wordpress using the firebase ui web interface or the reverse which is the sync wordpress to firebase using the wordpress login & register form.

**Comment by dalenguyen** [comment]
Creating Firebase users from WordPress is not supported at this moment. However, existing users can be migrated to Firebase. After that, via the plugin or custom authentication, users will be created in both systems. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/extentions/firebase-users.html
