### ISSUE TITLE
Be able to search others informations in a collection

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#46]
**Is your feature request related to a problem? Please describe.**
 Now a days, all the shortcode we can search for the document id.
I think that will be goog if we can search for all the informations. 
For example:

[firestore class='your-class-name' collection_name='string'  document_search='email' document_name='string@gmail.com' display_fields='email,displayName,role,uid']

**Comment by dalenguyen** [comment]
Will be added in v1.1.0
