### ISSUE TITLE
Firebase SMS Phone verification

### ISSUE THREAD

**Issue by kazmetika** [dalenguyen/firebase-wordpress-plugin#48]
Hi!

Do you plan to add SMS verification (Register user, update profile)?

BR

**Comment by dalenguyen** [comment]
Hi @kazmetika, the plugin uses FirebaseUI Web and it does support Phone Authentication. I will add it to the roadmap.

**Comment by kazmetika** [comment]
Hi! 

Sorry for the additional questions, but it's important for me to buy the plugin.

You've written "Authentication", and what about "verification"?

For example - Verify the phone number via SMS of a newly registered user in WordPress or WooCommerce.

As I know FirebaseUI could, but it's needed using Recaptcha or some coding?

https://firebase.google.com/docs/auth/web/phone-auth

I wanna build Free Directory Listing service and important thing - I need registration users by phone number (exclude cheaters, spammers and etc)

BR

**Comment by dalenguyen** [comment]
@kazmetika Sure, I will test the phone feature at the end of this week and let you know.

**Comment by kazmetika** [comment]
I appreciate it! See you

**Comment by dalenguyen** [comment]
@kazmetika, I added phone authentication. However, it will not able to log in to WordPress for now because WordPress still needs an email to register. However, user can log in to Firebase on WordPress.

**Comment by dalenguyen** [comment]
Will be available in v1.0.0
