### ISSUE TITLE
Not logged in message

### ISSUE THREAD

**Issue by rmidson** [dalenguyen/firebase-wordpress-plugin#5]
Can I first say, thank you for this plugin. If you keep developing this I think you are onto something very powerful and profitable for you. Great start!

One thing I would really like right now is a short code to show content if you are not logged in. So exactly the same way as it shows content if you are but the opposite. This way we can have a message saying something like "Login to see the rest of the page" if they are not logged in.

This would be my first request. 

The second request would be some message which said "sorry those login details were not correct" or similar when someone entered the wrong login details.

Great stuff so far though!

**Comment by dalenguyen** [comment]
Hi @rmidson, thanks for making the request. I think these do make sense, and I will work to update it :)

**Comment by rmidson** [comment]
Superb! Looking forward to testing. Thanks.

**Comment by rmidson** [comment]
Great stuff! Works really well! I will put it to the test.

**Comment by rmidson** [comment]
Hi. Been trying it. It's great.

Just one thought. In the same way as the signout button disappears when you sign out, can the login form disappear when you login succesfully?

I tried putting [firebase_show_not_login] around the [firebase_login] shortcode just in case to see if it would only appear when a user was logged out but that didn't seem to be a solution.

Great work.

**Comment by dalenguyen** [comment]
Hi @rmidson, please update the plugin to version 0.5.1 in order to hide the login form. If you have another request, you can create a new ticket for it. Thanks ;)
