### ISSUE TITLE
How to get the latest versions installed?

### ISSUE THREAD

**Issue by Neccer** [dalenguyen/firebase-wordpress-plugin#50]
How is the latest versions of the plugin installed? I have read though the docs, but cannot find any info about updating. 

Du the whole plugin need to be deleted and reinstalled? Or can it be done in a easier way?

-Thanks

**Comment by dalenguyen** [comment]
Hi @Neccer, you can do it by overriding the plugin folder. It can be done through an FTP client such as https://filezilla-project.org/

By doing this, you don't have to reenter the existing information.
