### ISSUE TITLE
Add forgot password 

### ISSUE THREAD

**Issue by elmcapp** [dalenguyen/firebase-wordpress-plugin#51]
should add forgot password button or link  to form when using shortcode for custom form. 
![add](https://user-images.githubusercontent.com/64275658/82284158-5cbfa980-9966-11ea-9b61-dcabac797ea5.png)

**Comment by dalenguyen** [comment]
Fixed in v0.20.0

**Comment by elmcapp** [comment]
Your are the best. Man you are a great programmer. Do you offer custom
jobs. I was thinking that you should make a full membership plugin with
paid subscriptions and also use with firebase login

**Comment by dalenguyen** [comment]
Thanks @elmcapp. I only offer short custom work that relates to the plugin.
