### ISSUE TITLE
Be able to include more than one shortcode for each page

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#52]
**Is your feature request related to a problem? Please describe.**
Actually, it is not able to include more than one shortcode for each page. If I try, the second Shortcode doenst show anything.

**Describe the solution you'd like**
This is a solution for Firestore or Realtime. Be able to include more than one shortcode. For example:

My account Page:

[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='email']

[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='Name']

[firestore class='circle' collection_name='seller' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='Price']

**Describe alternatives you've considered**

**Additional context**

**Comment by dalenguyen** [comment]
Fixed in v0.20.0
