### ISSUE TITLE
Shortcode Be able to bring a display or a image

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#53]
**Is your feature request related to a problem? Please describe.**
Actually,  is not possible to bring just a image. for example this shortcode:
[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' images='foto']
will give me all the data that I have in the collection.

**Describe the solution you'd like**
Conect de ShortCode just with a image, without Data (display);
[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' images='foto']

**Describe alternatives you've considered**

**Additional context**

**Comment by dalenguyen** [comment]
Fixed in v0.20.0
