### ISSUE TITLE
My choice to bring the name of the display

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#54]
**Is your feature request related to a problem? Please describe.**
Actually when I use the shortcode 100% of the time it bring me "The name of the display" and "Data". for example:
[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='email']
email: mcollina@gmail.com

[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='Name, email']
Name: Marcelo Collina
email: mcollina@gmail.com

**Describe the solution you'd like**

I choose when bring the name of the Data. Example:

[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='Name, email']
Marcelo Collina
mcollina@gmail.com

[firestore class='circle' collection_name='Users' document_name='hHmTfzqCcgTbMChH2K2dF8AoYES2' display_fields='email']
mcollina@gmail.com

**Describe alternatives you've considered**

**Additional context**

**Comment by dalenguyen** [comment]
Fixed in v0.20.0
