### ISSUE TITLE
Edit login or register form title labels. Edit form labels

### ISSUE THREAD

**Issue by elmcapp** [dalenguyen/firebase-wordpress-plugin#57]
Nice to be able to completely customize the login and registration form. 
As of now we are able to:
redirect to url.
change button text.
include inputs.

All we need now is to be able to change the forms Title and if needed change the labels
first name, last name and other input fields.

**Comment by dalenguyen** [comment]
This is added in v2.15.1

https://firebase-wordpress-docs.readthedocs.io/en/latest/auth/custom-registration-form.html
