### ISSUE TITLE
[Tutorial]How to change langue login/register

### ISSUE THREAD

**Issue by kushadapt** [dalenguyen/firebase-wordpress-plugin#58]
Hi guys, I figured out how to change the language of the firebaseui login.

If it helps.

integrate-firebase-PRO\includes\public

Open class.firebase.php

In line 58 don't change anything except if you want to get Arabic (ar), Farsi (fa), and Hebrew (iw).

In line 64

Change this 

`wp_enqueue_script('firebase_ui', 'https://www.gstatic.com/firebasejs/ui/4.5.0/firebase-ui-auth.js', array(), FIREBASE_WP_VERSION, false);`

By

`wp_enqueue_script('firebase_ui', 'https://www.gstatic.com/firebasejs/ui/4.5.0/firebase-ui-auth__{LANGUAGE_CODE}.js', array(), FIREBASE_WP_VERSION, false);`

KEEP THE  "_ _"

The list of available languages and their respective language codes can be found at [LANGUAGES.md.](https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md)

[Source](https://github.com/firebase/firebaseui-web#localized-widget)

Have a nice day.

**Comment by dalenguyen** [comment]
Thanks, @kushadapt. Remember it will disappear when you update the next version. Then you can manually edit it.

**Comment by dalenguyen** [comment]
FirebaseUI Web translation supported in v1.0.0
