### ISSUE TITLE
How about Login for Facebook / Google Authenticated Users ? 

### ISSUE THREAD

**Issue by kathanshah** [dalenguyen/firebase-wordpress-plugin#6]
How about Login for Facebook / Google Authenticated Users ?

**Comment by dalenguyen** [comment]
Hi @kathanshah, these are on the list of enhancement for this plugin. I will update in the future :)

**Comment by JanErikFoss** [comment]
Any ETA on this?

**Comment by dalenguyen** [comment]
@JanErikFoss I have two big projects that are going on until the beginning of Nov. I will start working on this enhancement after that.

**Comment by rabbie** [comment]
Hey Dalenguyen, any update on this one? I'm happy to pay for PRO to support you or even pay a donation for part of your dev time for this feature ?

**Comment by dalenguyen** [comment]
Hi @rabbie, I'm working on the PRO version. This version isn't secured enough for production usage.

**Comment by dalenguyen** [comment]
This feature is updated on PRO version 0.5.5 at https://firebase.dalenguyen.me
