### ISSUE TITLE
Multisite compatible

### ISSUE THREAD

**Issue by Rauljauregi** [dalenguyen/firebase-wordpress-plugin#60]
**Describe the bug**

The plugin it is not compatible for Multisite installations
**To Reproduce**
1. Create a Wordpress multisite installation
2. Install the plugin
3. Configure the plugin for a Firebase account
4. Login, or create an user. It will not work properly

**Expected behavior**
The main issue, is that users cannot  log in to WordPress, but other mal functions also happen

**Comment by dalenguyen** [comment]
@Rauljauregi, authentication support for multisite is available in v1.10.0. It's not available until next week.

**Comment by Rauljauregi** [comment]
Thank you Dale,
I am willing to check it out. Hope everithing will work properly. I will let you know.

Congrats in advance!
:)

**Comment by Rauljauregi** [comment]
Dear Dale,

I have installed new version but unfortunately it is not working. In facct the issues are the same as before. 

-You can login on one site of the multisite and you login through Firebase, but that is not enough because you keep not login on the rest of the sites of the multisite.
- Even if you login itiis just for that site and fot Firebase. But you are NOT logged to Wordpress. I mean you cannot log to wordpress

:(

Do you want me to open new issue?
Can I help to make the plugin works? I can give you credentials on the site in case you  need it.

**Comment by Rauljauregi** [comment]
I forgot to say that the plugin doesn't login to WooCommerce either
