### ISSUE TITLE
Confirmation email is never sent after user registration

### ISSUE THREAD

**Issue by darioherrera** [dalenguyen/firebase-wordpress-plugin#62]
I received the confirmation message but the user is never created.

**To Reproduce**
1. Go to the registration page
2.  Enter the data
3. It goes to the success page

**Expected behavior**
The user should receive a confirmation email and after the confirmation have to be shown in the users database in firebase. But this never happen.

**Comment by dalenguyen** [comment]
Hi @darioherrera, the confirmation is not sent by default. It can be requested as a new feature.

After registration, the User should exist in the Authentication tab in Firebase. For saving User to Realtime / Firestore, it's another feature that needs to be developed can be done through cloud functions that listen to User Create event. 

In case of Realtime / Firestore, which information should be saved how is it structure in your case?

**Comment by dalenguyen** [comment]
Hi @darioherrera, the plugin has the option to login via email without a password. Have you tried it?

**Comment by dalenguyen** [comment]
Confirmation is added in v1.11.0

https://firebase-wordpress-docs.readthedocs.io/en/latest/auth/register-login-form.html
