### ISSUE TITLE
I can't get class:getFirebaseUid to work.

### ISSUE THREAD

**Issue by kushadapt** [dalenguyen/firebase-wordpress-plugin#64]
Hello! Thanks again for this recent update!

I have a form that works very well so I would like to have the UID in documentId

so I added this line and deleted the old one but I still get INVALID in my database.

[hidden documentId class:getFirebaseUid "INVALID"]

Namely I updated the plugin to v1.0 by replacing the files on filezilla. I have the v1.0 of firebase pro on wordpress.

I haven't updated the firebase-wordpress-functions should I? If so, how do I do it, please?

Chrome console: 
JQMIGRATE: Migrate is installed, version 1.4.1
2firebase.js?ver=1.0.0:1 IF: Handle form submission for Firebase
firebase.js?ver=1.0.0:1 Form is valid, start saving data to Firebase
firebase.js?ver=1.0.0:1 Realtime data created with id: INVALID
firebase.js?ver=1.0.0:1 Form is valid, start saving data to Firebase
firebase.js?ver=1.0.0:1 Realtime data created with id: INVALID
firebase.js?ver=1.0.0:1 IF: Handle form submission for Firebase
firebase.js?ver=1.0.0:1 Form is valid, start saving data to Firebase
firebase.js?ver=1.0.0:1 Realtime data created with id: INVALID

Thanks to you :)

**Comment by dalenguyen** [comment]
Hi @kushadapt, were you logged in when saving form? User needs to log in in order to retrieve their firebase Uid. 

If you logged in with the plugin log form, and it still doesn’t replace the document_id, you can send the link to me. I can help to inspect it.

**Comment by kushadapt** [comment]
What a mistake you were right! I was not connected with firebaseui, I was connected with wordpress directly sorry.
Sometimes we make life difficult for simple things.

Thanks for enlightening me!
