### ISSUE TITLE
Could not load user data!

### ISSUE THREAD

**Issue by riturajpandey** [dalenguyen/firebase-wordpress-plugin#65]
**Describe the bug**
Not able to see/remove data

**To Reproduce**
Just set up firebase on WordPress
Go to the database tab click on real-time and enter a collection name

**Expected behavior**
Let show or add data

**Screenshots**
[screenshot](https://drive.google.com/file/d/1LNexcBmny-Z3ajDXRgxzxRQmZ-5iFHGl/view?usp=sharing)

**Desktop**
 Chrome browser

**Comment by dalenguyen** [comment]
Hi @riturajpandey, I think the configuration for settings is incorrect. Can you take a snapshot of that? You can sensor information in the picture. 

And it would be great if you can open the console log on the browser to check for error messages.

**Comment by riturajpandey** [comment]
<img width="1440" alt="Screenshot 2020-06-05 at 12 20 39 AM" src="https://user-images.githubusercontent.com/5201635/83850844-212b2a80-a72f-11ea-9b7b-3160f622107b.png">

It is showing me this error in the console.

I have cross-checked Base Domain,Dashboard and Frontend Token they are correct.I have used this [guide](https://firebase-wordpress-docs.readthedocs.io/en/latest/firebase-wordpress-integration.html)

**Comment by riturajpandey** [comment]
<img width="1438" alt="Screenshot 2020-06-05 at 1 23 26 PM" src="https://user-images.githubusercontent.com/5201635/83851295-c3e3a900-a72f-11ea-9d71-4a6b6273076e.png">
Snapshot of settings.

**Comment by dalenguyen** [comment]
Hi @riturajpandey, if the process is correct. Your firebase console should include those functions. 

![image](https://user-images.githubusercontent.com/14116156/83877709-034acf00-a709-11ea-9019-311660f2b5d0.png)

If those functions exist, and they still don't work. Send me an email at dale@dalenguyen.me, I will help you to inspect it.

**Comment by riturajpandey** [comment]
Ok let me check the functions.

**Comment by riturajpandey** [comment]
<img width="658" alt="Screenshot 2020-06-05 at 7 02 15 PM" src="https://user-images.githubusercontent.com/5201635/83881987-18524d00-a75f-11ea-9b7e-b38d873346de.png">
I don't have the functions with these names instead I am deploying my existing cloud functions which I have created.

Should I create functions like API-database etc?

Where can i find the definition of these functions?

**Comment by dalenguyen** [comment]
Hi @riturajpandey, 

It's in the plugin file when you first download. Please check the guide that I sent.

https://www.youtube.com/watch?v=D-xvzJ9K8jw

Thanks,

**Comment by Bikerflyeradmin** [comment]
can anyone tell me what the "base domain" is supposed to be?  I have finally got to the point where I have my frontend and dashboard tokens, but I do not know what to enter in the plugins settings where is calls for "base domain."  I have never heard that term before.  I just put my domain wikacy.com in there but it must be incorrect because I am getting the same "could not load user data" error when i search for a firebase document.

**Comment by dalenguyen** [comment]
@Bikerflyeradmin it's the cloud functions URL. Please watch the video at 7:44s. 

https://youtu.be/D-xvzJ9K8jw?t=442

@riturajpandey did you manage to deploy the functions?

**Comment by Bikerflyeradmin** [comment]
No, when I entered the command in the user guide to deploy the functions it gave me an error saying not found, or file not found or something to that effect.  Please help.

**Comment by Bikerflyeradmin** [comment]
Can someone tell me what I have to do in firebase to get my "base domain" to show up the way it does in the video guide.

**Comment by dalenguyen** [comment]
> No, when I entered the command in the user guide to deploy the functions it gave me an error saying not found, or file not found or something to that effect.  Please help.

Could you please take a snapshot of the error and steps that you did? It’s easier to figure out what happens.

**Comment by dalenguyen** [comment]
Closed due to inactivity.

**Comment by Bikerflyeradmin** [comment]
Im trying to tackle this again.  I would really like to get this plugin to
work.  Here is the error message I get when I try to install the functions
with the command you provided in the tutorial.

C:\Users\owner>npm i -g firebase-tools
npm WARN deprecated request@2.88.2: request has been deprecated, see
https://git
hub.com/request/request/issues/3142
C:\Users\owner\AppData\Roaming\npm\firebase ->
C:\Users\owner\AppData\Roaming\np
m\node_modules\firebase-tools\lib\bin\firebase.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2
(node_modules\fi
rebase-tools\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@
2.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"}
)

+ firebase-tools@8.4.3
added 3 packages from 5 contributors, removed 4 packages and updated 13
packages
 in 48.061s

C:\Users\owner>node --version
v14.4.0

C:\Users\owner>cd functions/ npm install
The system cannot find the path specified.

C:\Users\owner>

**Comment by Bikerflyeradmin** [comment]
im getting the same "could not load user data" error

JQMIGRATE: Migrate is installed, version 1.4.1
/wp-admin/wikacy.com/api-database/v1/getDoc:1 Failed to load resource: the
server responded with a status of 404 (Not Found)
firebase-admin.js?ver=1.0.0:1 Could not load user data!
t.showFirebaseErrorMessage @ firebase-admin.js?ver=1.0.0:1
jquery.js?ver=1.12.4-wp:4 POST
https://wikacy.com/wp-admin/wikacy.com/api-database/v1/getDoc 404 (Not
Found)
send @ jquery.js?ver=1.12.4-wp:4
ajax @ jquery.js?ver=1.12.4-wp:4
u @ firebase-admin.js?ver=1.0.0:1
o @ firebase-admin.js?ver=1.0.0:1
dispatch @ jquery.js?ver=1.12.4-wp:3
r.handle @ jquery.js?ver=1.12.4-wp:3
firebase-admin.js?ver=1.0.0:1 Could not load user d
