### ISSUE TITLE
Put getFirebaseUid in all shortcode that we have in plugin

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#67]
**Is your feature request related to a problem? Please describe.**
Example:
 [firestore class='x' search_fields='criador' earch_operators='eq' search_conditions='getFirebaseUid' collection_name='Produtos' display_fields='categoria, sub_categoria, titulo, descricao, preco_original']

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

**Additional context**

**Comment by dalenguyen** [comment]
Fixed in v1.2.0
