### ISSUE TITLE
Allow us to search for content in a collection from data in another collection.

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#68]
**Is your feature request related to a problem? Please describe.**
Allow us to search for content in a collection from data in another collection.

For example:

I am logged in with user 1 in the Users table (with the data User code and email, for example) and when clicking the button open a collection where the field to be searched for is the email.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

**Additional context**

**Comment by dalenguyen** [comment]
Hi @mcollinar, can you give more detail on this. A drawing shows how it work will really help. Thanks,

**Comment by dalenguyen** [comment]
This is a tricky one. However, it can be done with a custom script. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/add-custom-scripts.html
