### ISSUE TITLE
Sorting the list of a collection by timestamp. And hide some by filters. Realtime Database.

### ISSUE THREAD

**Issue by bejisan** [dalenguyen/firebase-wordpress-plugin#71]
`Enhancement`  Would it be possible to display the list by blocks and sort it by a long value (timestamp) and then display it.

And maybe even apply filters to the display list by blocks on the wordpress frontend site. If a value is true and the filter is false... make the node disappear.

**Comment by dalenguyen** [comment]
Added orderBy to getting realtime database by blocks. It is based on `orderByChild()`.

`[realtime_blocks class='your-class-name' collection_name='blog' display_fields='title,description,more' images='url' order_by='title']`

The filter can come later. I will close this for now.

Available in v1.6.0

**Comment by bejisan** [comment]
Thanks a lot Dale

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
