### ISSUE TITLE
🐛 Inconsistent Post Type Collection Names When Using Dashes or Underscores

### ISSUE THREAD

**Issue by altechzilla** [dalenguyen/firebase-wordpress-plugin#73]
There's two glitches when syncing custom post types with Firebase.

If the post type has two words (with either an underscore or a dash), it renders that too instead of camel-casing it.

<img width="282" alt="Attachment" src="https://user-images.githubusercontent.com/8274669/85785090-78159580-b718-11ea-97fa-544385765a17.png">

I think they should be “wpMusicVideos” and “wpElementorLibraries” instead. It would be great if collection names could also be custom labeled, so that if you wanted to drop the **wp** or take a deeper level of control over your database structure, you have that option.

The other glitch was that the word “library” gets pluralized as “librarys” instead of “libraries”.

**Comment by dalenguyen** [comment]
The collection name will be based on the post type plural label in v1.5.0.

**Comment by altechzilla** [comment]
Does it remove dashes and underscores too? @dalenguyen

**Comment by dalenguyen** [comment]
@altechzilla Yes it does. 

Fancy-Cars -> wpFancyCars
Fancy_cars -> wpFancyCars
Fancy Cars -> wpFancyCars

**Comment by altechzilla** [comment]
Any reason they're prefixed with wp? Is there a case where the plugin would do a different prefix base?

**Comment by dalenguyen** [comment]
It's because it comes from WordPress and I don't want it to be a conflict with existing collection names in people database.

**Comment by altechzilla** [comment]
Gotcha, makes sense!
