### ISSUE TITLE
💡 Mass Push / Pull / Sync Data to Firebase

### ISSUE THREAD

**Issue by altechzilla** [dalenguyen/firebase-wordpress-plugin#75]
It would be great of there was an option to mass push / pull or sync data for all enabled custom post types, taxonomies (once supported), users, etc.

**Comment by dalenguyen** [comment]
This can be done by bulk edit / delete posts. 

![image](https://user-images.githubusercontent.com/14116156/142740979-2d28f011-0def-4768-b6dc-70decd856ec5.png)
