### ISSUE TITLE
load a realtime database document using 'userId'  's value instead having to put the actual Id

### ISSUE THREAD

**Issue by bejisan** [dalenguyen/firebase-wordpress-plugin#76]
Would it be possible to display a userId (pushId) so that I can display a User fields.

Also how can I have a form that changes users fields in the realtime database keeping the same userId and not creating a new pushId for the form.

I guess it comes to being able to make any form tape into a specific pushId so that people can modify its values

**Comment by dalenguyen** [comment]
Hi @bejisan, userID can be generated automatically after they log in by putting a documentId field. Is it what you are looking for?

https://firebase-wordpress-docs.readthedocs.io/en/latest/database/save-data-realtime-firestore.html

**Comment by bejisan** [comment]
Yes It does work I get the right User's info rewritten, I lose some in the process, but it works.

However it works with firebaseweb-ui getCurrentUserId.

How could we modify a documentId after clicking on one element of the list. In my android app, I have documentChosen put EXTRA INTENTS to get to modify its value in another activity.

**Comment by bejisan** [comment]
like ...

benevolat65
    |_actions
            |_-MAQX0nkNBmsd1bKq5zg
                    |_actionId: "-MAQX0nkNBmsd1bKq5zg"
            |_49545470-b49d-11ea-89e6-958f74228115
                    |_actionId: "49545470-b49d-11ea-89e6-958f74228115"
    |_conseils
           |_-M9UxGrC0hJJBtNrw9Hu
                    |_conseilId: "-M9UxGrC0hJJBtNrw9Hu"
    |_recherches
           |_-M9Oy2VS36qLLKUD8_d8
                    |_rechercheId: "-M9Oy2VS36qLLKUD8_d8"
    |_users
          |_rFwo9I4mr0V7cdD3dGkWwaxeUly2
                    |_userId: "rFwo9I4mr0V7cdD3dGkWwaxeUly2"
    |_wpPages


i would need a way to edit any actions, conseils, or recherches
