### ISSUE TITLE
It would be good if we could access Storage

### ISSUE THREAD

**Issue by MarkHoath** [dalenguyen/firebase-wordpress-plugin#8]

**Comment by dalenguyen** [comment]
Hi @MarkHoath , could you give me an example of what you are going to this feature for? Thanks,

**Comment by stayhomemom240** [comment]
Is there no access to storage? I need my users to store music, photos, and such in their accounts, if they are stored in Wordpress will this secure them from other users?

**Comment by dalenguyen** [comment]
@stayhomemom240, I'm planning to add storage access to the frontend, so logged in users can upload photos or else. It won't be stored in WordPress media, rather, it will be stored in Firebase storage. You have to edit your security rules to make sure that it's secured. 

Please bookmark this site for more updates: https://integrate-firebase-pro.dalenguyen.me

**Comment by forTheSakeOfLogic** [comment]
no storage support yet?

I am looking for a way to be able to display images from my firebase storage on my wordpress site dynamically based on the logged in user.

**Comment by dalenguyen** [comment]
Hi @forTheSakeOfLogic, basically after the user logs in, if they have the permission, they can access the image now. Can you provide the structure of the images and how you would like to show them on WordPress?

**Comment by emailsubjekt** [comment]
I'm interested in this too, however I haven't got the site running yet. I've tried using the firebase authentication plugin but it didn't work. Then I tried https://firebase-wordpress-docs.readthedocs.io/en/stable/shortcode-list.html and saw that the official docs for that plugin https://firebase.dalenguyen.me/docs --> https://firebase.dalenguyen.me/assets/images/firebase-setting.png  --> , don't match as there's aren't 6 options but only 3 in reality when the plugin is opened in wordpress. It's also under settings option and not listed as one of the options on the left side board. 
Also I have no clue where to go from here after copying the API Key, AuthDomain, Database URL and Project Id from Firebase into Wordpress plugin. How do I now pull the data from my firebase realtime database onto the website? 




--

**Comment by dalenguyen** [comment]
Hi @emailsubjekt, the firebase-wordpress-docs is mainly for the PRO version. I should create an example for pulling file from Storage. 

As you can see in the display data section, it will be done through a shortcode. And check the console log for any error from the plugin or firebase.

**Comment by MarkHoath** [comment]
Closed
