### ISSUE TITLE
Custom Meta Data Support

### ISSUE THREAD

**Issue by altechzilla** [dalenguyen/firebase-wordpress-plugin#80]
I noticed that the plugin doesn't sync custom meta to Firebase, which would be extremely useful. Any chance to make that happen @dalenguyen ? There's a plugin called Post Meta Inspector which has some functions that may help get that meta from the database.

**Comment by dalenguyen** [comment]
Thanks @altechzilla, I will take a look at this at the weekend.

**Comment by dalenguyen** [comment]
Hi @altechzilla, are you using Advanced Custom Fields to create custom meta?

**Comment by altechzilla** [comment]
Using jetEngine, but I think it should support custom meta regardless of the plugin used.

**Comment by dalenguyen** [comment]
Added in v1.6.0. Custom fields will be under custom_fields. 

![image](https://user-images.githubusercontent.com/14116156/87228364-c066c180-c36e-11ea-8f06-39a196809db5.png)
