### ISSUE TITLE
Developer API

### ISSUE THREAD

**Issue by altechzilla** [dalenguyen/firebase-wordpress-plugin#81]
It would be great if there was a developer API (actions and filters) that allows connecting various Firebase stuff throughout other plugins / themes, for example:

## Firestore

**Get a Firestore Collection**
`firebase()->firestore->get_collection( $collection_id, $args = array() );`

**Get a Firestore Collection Object**
`firebase()->firestore->get_item( $collection_id, $post_id, $args = array() );`

**Get a Firestore Collection Object Field**
`firebase()->firestore->get_field( $collection_id, $post_id, $field_id, $args = array() );`

## Users

**Getting a User from Firebase**
`firebase()->users->get( $user_id, $args = array() );`

**Signing up a user to Firebase**
`firebase()->users->register( $user_id, $args = array() );`

## Elements

**Showing the social authentication buttons**
`firebase()->elements->users->register->social( $args = array() );`

That way the plugin would open the door towards custom integrations, such as creating custom Firebase Elementor blocks, dynamic tags, or simply referencing data programmatically more easily without using shortcodes.

The `firebase()` function could be the instance that holds everything.

Maybe the functions are already there but not documented.

Just a couple of thoughts, but it would be great if there was an easier way

**Comment by dalenguyen** [comment]
Thank @altechzilla, It's a great suggestion. I will definitely look into this.

**Comment by dalenguyen** [comment]
Hi @altechzilla, I decided to go with the filter hooks when interacting with Firebase. Here is an example. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/hooks/filters.html
