### ISSUE TITLE
Firebase Storage

### ISSUE THREAD

**Issue by hgalarreta** [dalenguyen/firebase-wordpress-plugin#82]
Hello. I would appreciate some guide to upload an image to **Storage**, and later read it somewhere else.
I can make the code in js. But I need help with the configuration; in your PRO plugin we have apiKey, authDomain, databaseURL, but no access to the storageBucket. 

So, how to start with Storage. Thank you for your support.

**Comment by dalenguyen** [comment]
Hi @hgalarreta, storage bucket is added in v1.7.0, and will be available by end of the weekend.
