### ISSUE TITLE
Allow easy customization of collection names sent to firebase. 

### ISSUE THREAD

**Issue by Bikerflyeradmin** [dalenguyen/firebase-wordpress-plugin#83]
I just think it would be a good idea to chose the collection name of the data being sent to firebase, along with the childkeys.  For example, my app uses the collection name "posts," but the WordPress posts are being sent to firebase as wpPosts.  Also, there is a lot of extra data in the posts that I don't need sent to firebase.  It would be nice if we could chose what data gets sent, and the label if the childkeys it gets sent under.

Also, it would be nice to send the firebase uid of the post author in a child key under the post data.

Please if it isn't to much trouble try to implement this.  Thanks you so much!

**Comment by dalenguyen** [comment]
Thanks @Bikerflyeradmin, I will add the author info in the next update.

**Comment by Bikerflyeradmin** [comment]
Awesome!  That would be great!  Oh, and I figured out how to style the data
from firebase!

**Comment by dalenguyen** [comment]
Author data is added in v1.9.0

**Comment by Bikerflyeradmin** [comment]
Do I have to update the functions as well, or just the plugin, and if I
just upload the new plugin via ftp will it overwrite without losing my
settings and configurations?

**Comment by Bikerflyeradmin** [comment]
Thank you, by the way!  But I would still like to register new users in the
app via the API.  Do you recommend a good oAuth plugin to use?

**Comment by Bikerflyeradmin** [comment]
Ok, then perhaps an oAuth plugin is not necessary to utilize your plugins
API user registration endpoint, since you don't know of one.

Can you provide further guidance on the plugins user registration endpoint,
such as whether authentication to the server is needed, and how to set the
body and the headers of the request?

Thanks for the new features!

**Comment by Bikerflyeradmin** [comment]
Dale, do you possibly have a video tutorial on how to create the contact
forms for users to manage their firebase data?  In your user guide, the
example form looks like shortcodes, but I can't find any way to create form
feilds with shortcodes.

Any help?

**Comment by Bikerflyeradmin** [comment]
Nevermind for now, I think I found it in your answer to the other guys
question about it.  You see, I already use forminator because they made a
custom front end story post form for me, and I really don't want to upload
another plugin.  So I am trying to create a form in forminatornso users on
the site can create and manage a character in the app, and also edit their
stories.

**Comment by Bikerflyeradmin** [comment]
Nevermind again, I couldn't figure it out from that either.  Man, Dale,
when I figure all this out I am going to volunteer to help you with your
user guide a little.  I am good at teaching things step by step and
actually explaining things because I have had such a hard time with
tutorials that don't teach anybody anything.

**Comment by Bikerflyeradmin** [comment]
I'm not going to even dare trying to update the plugin with such a lack of
guidance and mess up everything I have achieved.  The user guide says to
read the readme file to figure out if we need to update the functions, but
the readme file doesn't say anything about it.
