### ISSUE TITLE
No Storage Bucket defined - V 1.7

### ISSUE THREAD

**Issue by hgalarreta** [dalenguyen/firebase-wordpress-plugin#84]
**Describe the bug**
Not sure if it's a bug, but I configured the Bucket Storage with: "my-app.appspot.com" and checked the Storage option as described in the instructions; but when using a simple code to update an image to firebase Storage, I get the "Uncaught Error: No Storage Bucket defined in Firebase Options.”

To reproduce the behavior: On an empty wordpress page, using html editor:

```
<input type="file" id="photo">
<img id="image">
<button onclick="uploadImage()">Upload Image</button>
  <script src="https://www.gstatic.com/firebasejs/7.7.0/firebase-storage.js"></script>
```

```
<script>
    console.log(firebase);
 function uploadImage() {
      var ref = firebase.storage().ref();
      const file = document.querySelector("#photo").files[0];
      const name = +new Date() + "-" + file.name;
      const metadata = {
        contentType: file.type
      };
      const task = ref.child(name).put(file, metadata);
      task
        .then(snapshot => snapshot.ref.getDownloadURL())
        .then(url => {
          console.log(url);
          document.querySelector("#image").src = url;
        })
        .catch(console.error);
    }
</script>
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome, safari

**Additional context**
This is the sample page:
https://asisteme-peru.com/storage-test

**Screenshots**
![image](https://user-images.githubusercontent.com/49572586/87970799-e1739480-ca89-11ea-98cf-e611e7b1a9db.jpeg)
![image](https://user-images.githubusercontent.com/49572586/87985265-e8f26800-caa0-11ea-9ced-2293cffba807.jpeg)

**Comment by dalenguyen** [comment]
Hi @hgalarreta, the plugin already added storage script, so you don't have to append it yourself. 

```
// this can be removed from your script.
<script src="https://www.gstatic.com/firebasejs/7.7.0/firebase-storage.js"></script>
````

![image](https://user-images.githubusercontent.com/14116156/87988639-ac2d6d80-caae-11ea-8ea4-4de4921bf377.png)

`firebase.storage()` is available in the console log. 

I saw a misconfigured in the firebase initialization. It will be fixed and released in a few hours. Thanks for your ticket.

**Comment by hgalarreta** [comment]
Perfecto. works as a charm, thanks. Now the only thing missing is custom notifications, like to a specific token hehe
