### ISSUE TITLE
Not creating wordpress user when signup

### ISSUE THREAD

**Issue by vkgven** [dalenguyen/firebase-wordpress-plugin#85]
Hi,

I am developer trying to install Integrate Firebase PRO plugin brought by my client.

I have successfully installed it but it's not creating wordpress user when we signup..

Process I Did:
1. I installed and configured Integrate firebase pro.
2. I can create firebase users using this form [firebaseui_web][/firebaseui_web]
3. In Firebase->Auth I checked Allow Login to WP Dashboard. But it is not creating wp users.

Please help me in getting the user created in WordPress.

Thanks in advance,
Vladimir

**Comment by dalenguyen** [comment]
Should be resolved.
