### ISSUE TITLE
Creates a new user instead of getFirebaseUid since 1.6.0

### ISSUE THREAD

**Issue by bejisan** [dalenguyen/firebase-wordpress-plugin#86]
**Describe the bug**
When using `[hidden userId class:getFirebaseUid "INVALID"]` it creates a new userId when submiting the form, not rewriting over the current userId.

`<input type="hidden" name="userId" value="KimUQZsGmud9MTLCeri1stWvv403" class="wpcf7-form-control wpcf7-hidden getFirebaseUid"> `

`KimUQZsGmud9MTLCeri1stWvv403` is the right userId to rewrite over.... but it does creates a new user node in Firebase Realtime Database `b993fda0-cea9-11ea-bc09-fd7f56cfd416`

```
users
    |__ b993fda0-cea9-11ea-bc09-fd7f56cfd416
         |__ userFirstName: "Benjamin"
         |__ userId: "KimUQZsGmud9MTLCeri1stWvv403"
```

Which was working in the previous version of your plugin.

**Comment by dalenguyen** [comment]
Hi @bejisan, the node is defined by `documentId` field. Not `userId`. It works as intended.

**Comment by bejisan** [comment]
Yeah, my bad. Nevermind this message.
