### ISSUE TITLE
Please add built in forms where we can select the collection name we want users to access as well as link fields in the form with certain child keys in firebase.  If you can't do this, can you please explain in the user guide how we are to configure the form fields so that they update the data located under certain childkeys in firebase.

### ISSUE THREAD

**Issue by TheWizardofWikacy** [dalenguyen/firebase-wordpress-plugin#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

**Additional context**

**Comment by dalenguyen** [comment]
Should be done via custom scripts. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/add-custom-scripts.html
