### ISSUE TITLE
 firebase.User#updatePassword

### ISSUE THREAD

**Issue by steveabouem** [dalenguyen/firebase-wordpress-plugin#9]
Hi Dale

I'm brand new to using Firebase . I have a quick question.
My team has a mobile app, supported by Firebase. They asked me to set up a **"forgot password"** page on their WordPress website.Their users will be redirected to this page when they click on  "forgot password" in the mobile app. I made a page with a simple form ( email, new password, confirm new password). 

I want to update the user password in firebase.auth. For that I apparently need to call the  **firebase.User#updatePassword** function, to use the password entered in the form  to update the user matching the email entered in the form. 

My question is this:  Will the transaction work if I write my code in the Wordpress Custom CSS section? 
Thank you

**Comment by dalenguyen** [comment]
@steveabouem, I have updated the plugin for support the reset password yet. It's possible and you can put it anywhere on your WP site.

**Comment by steveabouem** [comment]
Thanks a lot Dale! I appreciate the prompt response:)

**Comment by dalenguyen** [comment]
This is now can be done with the PRO version. https://firebase.dalenguyen.me/
