### ISSUE TITLE
Show a information of two collection in one search.

### ISSUE THREAD

**Issue by mcollinar** [dalenguyen/firebase-wordpress-plugin#90]
Hello,

I would like to request a feature.
I would like to show data from one collection and from there, search for information in another collection.

For example: I have a Products collection, there is a data called Uid, which shows the user who created this product. I would like that instead of showing the UID, it would show the Username. This name is in a collection that has the UID, called Users

**Comment by dalenguyen** [comment]
At this moment, this can only be achieved with the custom script. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/add-custom-scripts.html
