### ISSUE TITLE
Automatically generate user in Firestore or Realtime Database

### ISSUE THREAD

**Issue by cankorfali** [dalenguyen/firebase-wordpress-plugin#92]
**Is your feature request related to a problem? Please describe.**
When would you like to use just the firebase WebUI on WordPress, the firebase can create the WordPress user and firebase user however it can not create a user automatically in Firestore or Realtime Database, user can only be shown in Authentication tab.

**Describe the solution you'd like**
I would like to use just the firebase WebUI on WordPress and when users sign in with any login option, it can be created automatically on  Firestore or Realtime Database Collections.

**Comment by Bikerflyeradmin** [comment]
Yes I would love for this to be added as well.

**Comment by dalenguyen** [comment]
@cankorfali I have a question. Which user's fields you would like have in Firebase or Firestore?

**Comment by cankorfali** [comment]
Sorry for my late reply,  If I'm wrong please correct me, when User sign up, it's creating on Authentication Tab and I think the Authentication Tab fields are pretty enough for starters. I assumed that after that the user data creation on Firebase or Firestore, I could add custom fields to related users like "My Favorites/Lists/Bookmarks" and could be possible to get users custom fields with related UID. 

Fields: User UID, Providers(Sign-up option), Identifier(E-mail), Full Name

Additionally, If I would like to add custom fields on firebase WebUI like, "gender", "birthday.., could it be also possible to create those fields on Firestore or Firebase? 

Thanks a lot for your support!

**Comment by dalenguyen** [comment]
This is available in v1.14.0

https://firebase-wordpress-docs.readthedocs.io/en/latest/firebase/users-to-firebase.html
