### ISSUE TITLE
Dashboard/Frontend API Secret Token help needed

### ISSUE THREAD

**Issue by kikaua** [dalenguyen/firebase-wordpress-plugin#93]
Hello everyone.  I have the Integrate Firebase PRO (v1.9.0) installed and configured correctly with Base Domain and Dashboard/Frontend API Secret Token.  From WordPress/Firebase Database tab I can put in users and a UID and get returned results as expected.

From a WordPress page I can login with Firebase email and passwords, BUT with the following:

[firebase_login button_text='Signin' redirect='/firebase']

[firebase_greetings][/firebase_greetings]

[firebase_error class='your-class-name'][/firebase_error]

[realtime_col class='your-class-name' collection_name='users' display_fields='UserID,firstName,lastName,planType,langOne,langTwo,Credist']

[firebase_show class='your-class-name']This message is only for logged in users![/firebase_show]
[firebase_logout][/firebase_logout]

I do see the greeting and the logout button, but I do NOT see the following to return: 

[realtime_col class='your-class-name' collection_name='users' display_fields='UserID,firstName,lastName,planType,langOne,langTwo,Credist']

I see the note "Remember to set the security rule, so anyone can read your document.", but I am not clear if this is a Firebase rule and if it is can I get a sample of the allow rule to use?

Thanks in advance.

**Comment by dalenguyen** [comment]
Hi @kikaua, the rule should be appropriately set. It is for everyone if the collection is public or testing. 

Is there any error or warning in the browser console log? And do you have a test link for this?

**Comment by kikaua** [comment]
@dalenguyen url: https://www.explico.ai/firebase user: sschroedl@gmail.com and passwd: asdfasdf  From firebase function logs I see requests in function logs for WordPress>Firebase>Database requests, but no requests from the url i just shared.

**Comment by dalenguyen** [comment]
Hi @kikaua, there is an error in the console log that may causes the issue. 

![image](https://user-images.githubusercontent.com/14116156/89109336-3d390880-d40e-11ea-89e2-c8f1e426d46d.png)

Could you please sure the configuration on **Firebase > General** is exactly the same in your firebase project? Especially the **database URL**.

**Comment by kikaua** [comment]
That fixed it, but also very odd as i copied and pasted all the info, but somehow the url added the www. to the base url.

**Comment by dalenguyen** [comment]
Nice. I'm glad that it's fixed :D
