### ISSUE TITLE
Upgrade instructions?

### ISSUE THREAD

**Issue by kikaua** [dalenguyen/firebase-wordpress-plugin#94]
I got your email with the announcement of Integrate Firebase PRO (v1.10.0), and I am new (July 28, 2020).  I went back to the purchase page and logged in via google, but the download link is for Integrate Firebase PRO (v1.9.0).  Where do I find the 1.10.0 download link?

Thanks

FYI: I think this is a code typo from user guide: Retrieve Data and Display on WordPress, Step 2: Add custom javascript file, **custom_firebaes**

**Comment by dalenguyen** [comment]
Thank @kikaua, it should be fixed now. You can download it again in the purchase page.
