### ISSUE TITLE
Quote for paid features update

### ISSUE THREAD

**Issue by kikaua** [dalenguyen/firebase-wordpress-plugin#99]
Posting here as I can not find an email to reach you.

Seeking a quote for changes to shortcode realtime_col (or recommendation of a better way) for Realtime to allow returned results must have a child (Users>UID>AdminLevel) of X and a second child (Users>UID>Organization) of Y.  This would make it so the logged-in user is an admin of the organization to see the list of users for their organization.  Then the list from realtime_col would have the far right-hand column would have three icons (view, edit, delete).  lastly, an add button to add a new user to the Auth and Database from.

This needs to be secure to not allow a different admin from a different organization to have access to see in the clear the realtime db from firebase.

Steven

**Comment by dalenguyen** [comment]
Hi @kikaua, the plugin is built on top of Firebase & WordPress. Feel free to have an inhouse developer or freelance to accomplish complicated tasks with custom scripts. Please have a look at the Developer section. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/retrieve-data.html
